import 'dart:convert';

import 'package:http/http.dart' as http;

import '../utils/app_logger.dart';

enum SonarTubeItemKind { video, channel, playlist }

class _InnerTubeHttpFailure implements Exception {
  const _InnerTubeHttpFailure(this.statusCode);

  final int statusCode;

  @override
  String toString() => statusCode.toString();
}

class SonarTubeItem {
  const SonarTubeItem({
    required this.kind,
    required this.id,
    required this.title,
    required this.url,
    this.channel,
    this.channelId,
    this.thumbnailUrl,
    this.duration,
    this.published,
    this.views,
    this.subscribers,
    this.handle,
    this.description,
    this.isLive = false,
  });

  final SonarTubeItemKind kind;
  final String id;
  final String title;
  final String url;
  final String? channel;
  final String? channelId;
  final String? thumbnailUrl;
  final String? duration;
  final String? published;
  final String? views;
  final String? subscribers;
  final String? handle;
  final String? description;
  final bool isLive;
}

class SonarTubePage {
  const SonarTubePage({
    required this.items,
    required this.page,
    this.nextToken,
  });

  final List<SonarTubeItem> items;
  final int page;
  final String? nextToken;

  bool get hasMore => nextToken != null && nextToken!.isNotEmpty;
}

class SonarTubeResolvedMedia {
  const SonarTubeResolvedMedia({
    required this.title,
    required this.audioUrl,
    this.videoUrl,
    this.channel,
  });

  final String title;
  final String audioUrl;
  final String? videoUrl;
  final String? channel;
}


class SonarTubeComment {
  const SonarTubeComment({
    required this.id,
    required this.text,
    this.author,
    this.published,
    this.likes,
    this.authorChannelId,
    this.thumbnailUrl,
    this.replyCount = 0,
    this.pinned = false,
  });

  final String id;
  final String text;
  final String? author;
  final String? published;
  final String? likes;
  final String? authorChannelId;
  final String? thumbnailUrl;
  final int replyCount;
  final bool pinned;
}

class SonarTubeCommentsPage {
  const SonarTubeCommentsPage({
    required this.items,
    required this.page,
    this.nextToken,
  });

  final List<SonarTubeComment> items;
  final int page;
  final String? nextToken;

  bool get hasMore => nextToken != null && nextToken!.isNotEmpty;
}


class SonarTubeTranscriptUnavailableException implements Exception {
  const SonarTubeTranscriptUnavailableException();
}

class SonarTubeTranscript {
  const SonarTubeTranscript({
    required this.text,
    this.title,
    this.language,
    this.autoGenerated = false,
    this.paragraphs = const [],
  });

  final String text;
  final String? title;
  final String? language;
  final bool autoGenerated;
  final List<String> paragraphs;
}

class SonarTubeService {
  static const _youtubeApiKey = 'AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vfUWA8808';
  static const _webClientVersion = '2.20260722.01.00';
  static const _androidClientVersion = '21.29.366';
  static const _androidUserAgent =
      'com.google.android.youtube/21.29.366 '
      '(Linux; U; Android 16; en_US; SM-S908E Build/TP1A.220624.014) gzip';
  static final Uri _youtubeSearchEndpoint = Uri.parse(
    'https://www.youtube.com/youtubei/v1/search'
    '?prettyPrint=false&key=$_youtubeApiKey',
  );
  static final Uri _youtubeBrowseEndpoint = Uri.parse(
    'https://www.youtube.com/youtubei/v1/browse'
    '?prettyPrint=false&key=$_youtubeApiKey',
  );
  static final Uri _youtubeNextEndpoint = Uri.parse(
    'https://www.youtube.com/youtubei/v1/next'
    '?prettyPrint=false&key=$_youtubeApiKey',
  );
  static final Uri _youtubePlayerEndpoint = Uri.parse(
    'https://www.youtube.com/youtubei/v1/player'
    '?prettyPrint=false&key=$_youtubeApiKey',
  );
  static const _compiledClientToken = String.fromEnvironment(
    'SONARPAD_ROUTE_CLIENT_TOKEN',
  );

  SonarTubeService({
    http.Client? client,
    Uri? endpoint,
    String? clientToken,
    bool enableDirectNavigation = true,
  }) : _client = client ?? http.Client(),
       endpoint =
           endpoint ?? Uri.parse('https://sonarpad.com/api/youtube_resolve.php'),
       _clientToken = clientToken ?? _compiledClientToken,
       _directNavigationEnabled = enableDirectNavigation;

  final http.Client _client;
  final Uri endpoint;
  final String _clientToken;
  final bool _directNavigationEnabled;
  String _youtubeLanguage = 'it';
  String _youtubeRegion = 'IT';

  void setLocaleName(String localeName) {
    final normalized = localeName.replaceAll('-', '_').toLowerCase();
    if (normalized == 'cs') {
      _youtubeLanguage = 'cs';
      _youtubeRegion = 'CZ';
    } else if (normalized == 'de') {
      _youtubeLanguage = 'de';
      _youtubeRegion = 'DE';
    } else if (normalized == 'en') {
      _youtubeLanguage = 'en';
      _youtubeRegion = 'US';
    } else if (normalized == 'es') {
      _youtubeLanguage = 'es';
      _youtubeRegion = 'ES';
    } else if (normalized == 'fr') {
      _youtubeLanguage = 'fr';
      _youtubeRegion = 'FR';
    } else if (normalized == 'pl') {
      _youtubeLanguage = 'pl';
      _youtubeRegion = 'PL';
    } else if (normalized == 'pt') {
      _youtubeLanguage = 'pt-PT';
      _youtubeRegion = 'PT';
    } else if (normalized == 'pt_br') {
      _youtubeLanguage = 'pt-BR';
      _youtubeRegion = 'BR';
    } else if (normalized == 'uk') {
      _youtubeLanguage = 'uk';
      _youtubeRegion = 'UA';
    } else if (normalized == 'zh' || normalized == 'zh_cn') {
      _youtubeLanguage = 'zh-CN';
      _youtubeRegion = 'CN';
    } else {
      _youtubeLanguage = 'it';
      _youtubeRegion = 'IT';
    }
  }

  Future<SonarTubePage> search(String query, {String? token, int page = 1}) {
    final trimmedQuery = query.trim();
    final fallbackQuery = <String, String>{
        'hl': _youtubeLanguage,
        'gl': _youtubeRegion,
        'q': trimmedQuery,
        'type': 'all',
        'format': 'json',
        if (token != null && token.isNotEmpty) 'token': token,
        'page': '$page',
      };
    if (!_directNavigationEnabled) {
      return _loadServerPage(fallbackQuery);
    }
    return _loadNavigationPage(
      operation: 'search',
      direct: () => _searchDirect(
        trimmedQuery,
        token: token,
        page: page,
      ),
      fallbackQuery: fallbackQuery,
    );
  }

  Future<SonarTubePage> browse(
    SonarTubeItem collection, {
    String? token,
    int page = 1,
  }) {
    if (collection.kind == SonarTubeItemKind.video) {
      throw ArgumentError('Un video non è una raccolta SonarTube.');
    }
    final seedVideoId = _mixSeedVideoId(collection);
    final fallbackQuery = <String, String>{
      'hl': _youtubeLanguage,
      'gl': _youtubeRegion,
      'browse': collection.id,
      'kind': collection.kind.name,
      'title': collection.title,
      'format': 'json',
      'seed': ?seedVideoId,
      if (token != null && token.isNotEmpty) 'token': token,
      'page': '$page',
    };
    if (!_directNavigationEnabled) {
      return _loadServerPage(fallbackQuery);
    }
    return _loadNavigationPage(
      operation: 'browse:${collection.kind.name}',
      direct: () => _browseDirect(
        collection,
        token: token,
        page: page,
        seedVideoId: seedVideoId,
      ),
      fallbackQuery: fallbackQuery,
    );
  }

  String? _mixSeedVideoId(SonarTubeItem collection) {
    if (collection.kind != SonarTubeItemKind.playlist ||
        !collection.id.startsWith('RD')) {
      return null;
    }
    final uri = Uri.tryParse(collection.url);
    final seed = uri?.queryParameters['v'];
    if (seed != null && RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(seed)) {
      return seed;
    }
    if (collection.id.length == 13) {
      final derived = collection.id.substring(2);
      if (RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(derived)) {
        return derived;
      }
    }
    return null;
  }

  Future<SonarTubeResolvedMedia> resolve(SonarTubeItem item) {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('È possibile risolvere soltanto un video.');
    }
    return resolveUrl(
      item.url.isEmpty ? item.id : item.url,
      fallbackTitle: item.title,
      fallbackChannel: item.channel,
    );
  }

  Future<SonarTubeResolvedMedia> resolveUrl(
    String url, {
    required String fallbackTitle,
    String? fallbackChannel,
  }) async {
    final trimmedUrl = url.trim();
    if (trimmedUrl.isEmpty) {
      throw ArgumentError.value(url, 'url');
    }
    final data = await _request({
      'url': trimmedUrl,
      'quality': 'best',
      'prefer': 'auto',
      'format': 'json',
    });

    final stream = _string(data['stream']);
    final streamVideo = _string(data['stream_video']);
    final streamAudio = _string(data['stream_audio']);
    if (stream == null) {
      throw const FormatException('Nessun flusso riproducibile disponibile.');
    }

    final hasSeparateStreams =
        streamVideo != null && streamAudio != null && stream == streamVideo;
    return SonarTubeResolvedMedia(
      title: _string(data['title']) ?? fallbackTitle,
      channel: _string(data['channel']) ?? fallbackChannel,
      audioUrl: hasSeparateStreams ? streamAudio : stream,
      videoUrl: hasSeparateStreams ? streamVideo : null,
    );
  }


  Future<SonarTubeItem> channelForVideo(SonarTubeItem item) async {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('video_required');
    }
    var channelId = item.channelId;
    var channelTitle = item.channel;
    if (channelId == null || channelId.isEmpty) {
      if (_directNavigationEnabled) {
        try {
          final data = await _playerMetadataDirect(item.id);
          channelId = _string(data['channelId']);
          channelTitle = _string(data['author']) ?? channelTitle;
        } catch (_) {
          // Il resolver server resta il fallback anche per l'apertura del
          // canale quando il risultato video non contiene già il channelId.
        }
      }
      if (channelId == null || channelId.isEmpty) {
        final data = await _request({
          'url': item.url.isEmpty ? item.id : item.url,
          'metadata': '1',
          'format': 'json',
        });
        channelId = _string(data['channel_id']);
        channelTitle = _string(data['channel']) ?? channelTitle;
      }
    }
    if (channelId == null || channelId.isEmpty) {
      throw const FormatException('channel_unavailable');
    }
    return SonarTubeItem(
      kind: SonarTubeItemKind.channel,
      id: channelId,
      title: channelTitle ?? item.channel ?? item.title,
      url: Uri.https('www.youtube.com', '/channel/$channelId').toString(),
      channel: channelTitle,
    );
  }

  Future<SonarTubeItem> refreshChannelMetadata(SonarTubeItem item) async {
    if (item.kind != SonarTubeItemKind.channel) {
      throw ArgumentError('channel_required');
    }
    if (_hasCompleteChannelMetadata(item)) return item;

    SonarTubeItem? refreshed;
    if (_directNavigationEnabled) {
      try {
        final data = await _searchInnerTube(item.title, type: 'channel');
        refreshed = _exactChannelFromItems(
          _extractNavigationItems(data),
          item.id,
        );
      } catch (error) {
        await AppLogger.log(
          'SonarTube: channel metadata direct refresh failed id=${item.id} '
          'error=$error',
        );
      }
    }

    if (refreshed == null) {
      try {
        final page = await _loadServerPage({
          'hl': _youtubeLanguage,
          'gl': _youtubeRegion,
          'q': item.title,
          'type': 'channel',
          'format': 'json',
          'page': '1',
        });
        refreshed = _exactChannelFromItems(page.items, item.id);
      } catch (error) {
        await AppLogger.log(
          'SonarTube: channel metadata server refresh failed id=${item.id} '
          'error=$error',
        );
      }
    }

    if (refreshed == null) return item;
    return _mergeChannelMetadata(item, refreshed);
  }

  bool _hasCompleteChannelMetadata(SonarTubeItem item) =>
      (item.handle?.trim().isNotEmpty ?? false) &&
      (item.subscribers?.trim().isNotEmpty ?? false);

  SonarTubeItem? _exactChannelFromItems(
    Iterable<SonarTubeItem> items,
    String channelId,
  ) {
    for (final candidate in items) {
      if (candidate.kind == SonarTubeItemKind.channel &&
          candidate.id == channelId) {
        return candidate;
      }
    }
    return null;
  }

  SonarTubeItem _mergeChannelMetadata(
    SonarTubeItem existing,
    SonarTubeItem refreshed,
  ) {
    String? prefer(String? newer, String? older) {
      final value = newer?.trim();
      return value != null && value.isNotEmpty ? value : older;
    }

    return SonarTubeItem(
      kind: SonarTubeItemKind.channel,
      id: existing.id,
      title: refreshed.title.trim().isNotEmpty
          ? refreshed.title
          : existing.title,
      url: prefer(refreshed.url, existing.url) ?? existing.url,
      channel: prefer(refreshed.channel, existing.channel),
      channelId: prefer(refreshed.channelId, existing.channelId),
      thumbnailUrl: prefer(refreshed.thumbnailUrl, existing.thumbnailUrl),
      duration: existing.duration,
      published: existing.published,
      views: existing.views,
      subscribers: prefer(refreshed.subscribers, existing.subscribers),
      handle: prefer(refreshed.handle, existing.handle),
      description: prefer(refreshed.description, existing.description),
      isLive: existing.isLive,
    );
  }

  Future<SonarTubeCommentsPage> comments(
    SonarTubeItem item, {
    String? token,
    int page = 1,
  }) async {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('video_required');
    }
    final data = await _request({
      'hl': _youtubeLanguage,
      'gl': _youtubeRegion,
      'url': item.url.isEmpty ? item.id : item.url,
      'comments': '1',
      'format': 'json',
      if (token != null && token.isNotEmpty) 'token': token,
      'page': '$page',
    });
    final rawItems = data['items'] is List ? data['items'] as List : const [];
    final items = rawItems
        .whereType<Map>()
        .map((raw) => Map<String, dynamic>.from(raw))
        .map((raw) {
          final id = _string(raw['id']);
          final text = _string(raw['text']);
          if (id == null || text == null) return null;
          return SonarTubeComment(
            id: id,
            text: text,
            author: _string(raw['author']),
            published: _string(raw['published']),
            likes: _string(raw['likes']),
            authorChannelId: _string(raw['author_channel_id']),
            thumbnailUrl: _string(raw['thumbnail']),
            replyCount: _int(raw['reply_count']) ?? 0,
            pinned: raw['pinned'] == true,
          );
        })
        .whereType<SonarTubeComment>()
        .toList(growable: false);
    return SonarTubeCommentsPage(
      items: items,
      page: _int(data['page']) ?? page,
      nextToken: _string(data['next_token']),
    );
  }


  Future<SonarTubeTranscript> transcribe(
    SonarTubeItem item, {
    String languageCode = 'auto',
  }) async {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('video_required');
    }
    Object? lastFailure;
    for (var attempt = 0; attempt < 2; attempt++) {
      try {
        final data = await _request(
          {
            'url': item.url.isEmpty ? item.id : item.url,
            'transcribe': '1',
            'timestamps': '1',
            'format': 'json',
            'lang': languageCode.trim().isEmpty ? 'auto' : languageCode.trim(),
          },
          allowApiError: true,
        );
        if (data['ok'] != true) {
          final error = _string(data['error']);
          if (error == 'no_captions' || error == 'no_track') {
            throw const SonarTubeTranscriptUnavailableException();
          }
          if (attempt == 0) {
            await Future<void>.delayed(const Duration(milliseconds: 250));
            continue;
          }
          if (error == 'empty_transcript') {
            throw const SonarTubeTranscriptUnavailableException();
          }
          throw Exception(error ?? 'transcript_failed');
        }
        final transcript = _string(data['transcript']);
        if (transcript == null || transcript.trim().isEmpty) {
          if (attempt == 0) {
            await Future<void>.delayed(const Duration(milliseconds: 250));
            continue;
          }
          throw const SonarTubeTranscriptUnavailableException();
        }
        final segmentTexts = (data['lines'] is List
                ? data['lines'] as List
                : const <dynamic>[])
            .whereType<Map>()
            .map((line) => _string(line['text']))
            .whereType<String>()
            .toList(growable: false);
        final plainText = segmentTexts.isEmpty
            ? transcript.trim()
            : segmentTexts.join(' ');
        return SonarTubeTranscript(
          text: plainText,
          title: _string(data['title']) ?? item.title,
          language: _string(data['lang']),
          autoGenerated: data['auto_generated'] == true,
          paragraphs: _groupTranscriptParagraphs(
            segmentTexts.isEmpty
                ? plainText.split(RegExp(r'\s+'))
                : segmentTexts,
          ),
        );
      } on SonarTubeTranscriptUnavailableException {
        rethrow;
      } catch (error) {
        lastFailure = error;
        if (attempt == 0) {
          await Future<void>.delayed(const Duration(milliseconds: 250));
          continue;
        }
      }
    }
    throw lastFailure ?? Exception('transcript_failed');
  }

  List<String> _groupTranscriptParagraphs(List<String> pieces) {
    final paragraphs = <String>[];
    final current = StringBuffer();
    for (final rawPiece in pieces) {
      final piece = rawPiece.trim().replaceAll(RegExp(r'\s+'), ' ');
      if (piece.isEmpty) continue;
      if (current.isNotEmpty) current.write(' ');
      current.write(piece);
      final text = current.toString();
      final sentenceEnd = RegExp(r'[.!?…][\"”’)]?$').hasMatch(piece);
      if ((text.length >= 220 && sentenceEnd) || text.length >= 420) {
        paragraphs.add(text);
        current.clear();
      }
    }
    if (current.isNotEmpty) paragraphs.add(current.toString());
    return paragraphs;
  }

  Future<SonarTubePage> _loadNavigationPage({
    required String operation,
    required Future<SonarTubePage> Function() direct,
    required Map<String, String> fallbackQuery,
  }) async {
    Object? directFailure;
    for (var attempt = 0; attempt < 2; attempt++) {
      try {
        final page = await direct();
        await AppLogger.log(
          'SonarTube: direct InnerTube $operation success '
          'attempt=${attempt + 1} page=${page.page} items=${page.items.length} '
          'hasMore=${page.hasMore}',
        );
        return page;
      } catch (error) {
        directFailure = error;
        await AppLogger.log(
          'SonarTube: direct InnerTube $operation failed '
          'attempt=${attempt + 1} error=$error',
        );
        if (attempt == 0) {
          await Future<void>.delayed(const Duration(milliseconds: 300));
        }
      }
    }

    await AppLogger.log(
      'SonarTube: direct InnerTube $operation unavailable; '
      'using server fallback host=${endpoint.host}',
    );
    try {
      final page = await _loadServerPage(fallbackQuery);
      await AppLogger.log(
        'SonarTube: server fallback $operation success '
        'page=${page.page} items=${page.items.length} hasMore=${page.hasMore}',
      );
      return page;
    } catch (fallbackFailure) {
      await AppLogger.log(
        'SonarTube: server fallback $operation failed error=$fallbackFailure',
      );
      throw Exception(
        'SonarTube navigation failed. '
        'direct=$directFailure; fallback=$fallbackFailure',
      );
    }
  }

  Future<SonarTubePage> _loadServerPage(Map<String, String> query) async {
    Object? lastFailure;
    for (var attempt = 0; attempt < 2; attempt++) {
      try {
        final data = await _request(query);
        final rawItems = data['items'] is List
            ? data['items'] as List
            : data['videos'] is List
            ? data['videos'] as List
            : const [];
        final items = rawItems
            .whereType<Map>()
            .map((raw) => _parseItem(Map<String, dynamic>.from(raw)))
            .whereType<SonarTubeItem>()
            .toList(growable: false);
        return SonarTubePage(
          items: items,
          page: _int(data['page']) ?? 1,
          nextToken: _string(data['next_token']),
        );
      } catch (error) {
        lastFailure = error;
        if (attempt == 0) {
          await Future<void>.delayed(const Duration(milliseconds: 300));
        }
      }
    }
    throw lastFailure ?? Exception('sonartube_page_failed');
  }

  Future<SonarTubePage> _searchDirect(
    String query, {
    String? token,
    int page = 1,
  }) async {
    final continuation = token?.trim() ?? '';
    if (query.isEmpty && continuation.isEmpty) {
      return SonarTubePage(items: const [], page: page);
    }

    final data = await _searchInnerTube(
      query,
      continuation: continuation,
      type: 'all',
    );
    var items = _extractNavigationItems(data);
    final nextToken = _findSearchContinuation(data);

    // Replica il resolver PHP: sulla prima pagina generale aggiunge davanti
    // i video della ricerca filtrata e, in coda, alcuni canali e playlist.
    if (continuation.isEmpty) {
      final known = <String>{
        for (final item in items) _navigationItemKey(item),
      };

      final supplements = await Future.wait([
        _trySearchSupplement(query, 'video'),
        _trySearchSupplement(query, 'channel'),
        _trySearchSupplement(query, 'playlist'),
      ]);

      final exactVideos = <SonarTubeItem>[];
      for (final item in supplements[0]) {
        if (item.kind != SonarTubeItemKind.video) continue;
        final key = _navigationItemKey(item);
        if (!known.add(key)) continue;
        exactVideos.add(item);
        if (exactVideos.length >= 20) break;
      }
      if (exactVideos.isNotEmpty) {
        items = [...exactVideos, ...items];
      }

      final extraKinds = [
        SonarTubeItemKind.channel,
        SonarTubeItemKind.playlist,
      ];
      for (var index = 0; index < extraKinds.length; index++) {
        final expectedKind = extraKinds[index];
        final extraItems = supplements[index + 1];
        var added = 0;
        for (final item in extraItems) {
          if (item.kind != expectedKind) continue;
          final key = _navigationItemKey(item);
          if (!known.add(key)) continue;
          items.add(item);
          added++;
          if (added >= 5) break;
        }
      }
    }

    if (items.isEmpty && query.isNotEmpty) {
      throw const FormatException('empty_direct_search_results');
    }
    return SonarTubePage(
      items: List.unmodifiable(items),
      page: page,
      nextToken: nextToken,
    );
  }

  Future<List<SonarTubeItem>> _trySearchSupplement(
    String query,
    String type,
  ) async {
    try {
      final data = await _searchInnerTube(query, type: type);
      return _extractNavigationItems(data);
    } catch (_) {
      // Le ricerche supplementari migliorano l'aderenza dei risultati, ma la
      // risposta generale resta valida anche se uno di questi tentativi fallisce.
      return const [];
    }
  }

  Future<Map<String, dynamic>> _searchInnerTube(
    String query, {
    String continuation = '',
    String type = 'all',
  }) {
    final payload = <String, dynamic>{
      'context': _youtubeBrowseContext(),
    };
    if (continuation.isNotEmpty) {
      payload['continuation'] = continuation;
    } else {
      payload['query'] = query;
      final params = _searchParamsForType(type);
      if (params != null) payload['params'] = params;
    }
    return _postInnerTube(_youtubeSearchEndpoint, payload, webClient: true);
  }

  Future<SonarTubePage> _browseDirect(
    SonarTubeItem collection, {
    String? token,
    int page = 1,
    String? seedVideoId,
  }) async {
    final continuation = token?.trim() ?? '';
    final isPlaylist = collection.kind == SonarTubeItemKind.playlist;
    final isGeneratedMix = isPlaylist && collection.id.startsWith('RD');
    final payload = <String, dynamic>{
      'context': _youtubeBrowseContext(),
    };

    if (continuation.isNotEmpty) {
      payload['continuation'] = continuation;
    } else if (isGeneratedMix) {
      var seed = seedVideoId?.trim() ?? '';
      if (seed.isEmpty && collection.id.length == 13) {
        final derived = collection.id.substring(2);
        if (RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(derived)) {
          seed = derived;
        }
      }
      payload['playlistId'] = collection.id;
      if (seed.isNotEmpty) payload['videoId'] = seed;
    } else if (isPlaylist) {
      payload['browseId'] = collection.id.startsWith('VL')
          ? collection.id
          : 'VL${collection.id}';
    } else {
      final uploadsId = collection.id.startsWith('UC')
          ? 'UU${collection.id.substring(2)}'
          : collection.id;
      payload['browseId'] = uploadsId.startsWith('VL')
          ? uploadsId
          : 'VL$uploadsId';
    }

    final data = await _postInnerTube(
      isGeneratedMix ? _youtubeNextEndpoint : _youtubeBrowseEndpoint,
      payload,
      webClient: true,
    );
    final videos = _extractNavigationItems(data)
        .where((item) => item.kind == SonarTubeItemKind.video)
        .toList(growable: false);
    if (videos.isEmpty && continuation.isEmpty) {
      // Un canale/playlist scelto dall'utente normalmente contiene almeno un
      // video. Se la risposta diretta cambia layout e il parser non riconosce
      // più nulla, considera il tentativo non riuscito e lascia spazio al
      // resolver server, che può essere aggiornato indipendentemente dall'app.
      throw const FormatException('empty_direct_browse_results');
    }
    return SonarTubePage(
      items: videos,
      page: page,
      nextToken: _findSearchContinuation(data),
    );
  }

  Future<Map<String, dynamic>> _playerMetadataDirect(String videoId) async {
    if (!RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(videoId)) {
      throw const FormatException('invalid_video_id');
    }
    final data = await _postInnerTube(
      _youtubePlayerEndpoint,
      {
        'context': {
          'client': {
            'hl': _youtubeLanguage,
            'gl': _youtubeRegion,
            'clientName': 'ANDROID',
            'clientVersion': _androidClientVersion,
            'androidSdkVersion': 33,
            'osName': 'Android',
            'osVersion': '16',
            'platform': 'MOBILE',
          },
        },
        'videoId': videoId,
        'playbackContext': {
          'contentPlaybackContext': {
            'html5Preference': 'HTML5_PREF_WANTS',
          },
        },
        'contentCheckOk': true,
        'racyCheckOk': true,
      },
      webClient: false,
    );
    final details = data['videoDetails'];
    if (details is! Map) {
      throw const FormatException('channel_unavailable');
    }
    return Map<String, dynamic>.from(details);
  }

  Map<String, dynamic> _youtubeBrowseContext() {
    return {
      'client': {
        'hl': _youtubeLanguage,
        'gl': _youtubeRegion,
        'clientName': 'WEB',
        'clientVersion': _webClientVersion,
        'platform': 'DESKTOP',
      },
    };
  }

  String? _searchParamsForType(String type) {
    return switch (type) {
      'video' || 'videos' => 'EgIQAQ==',
      'live' || 'stream' => 'EgJAAQ==',
      'channel' || 'channels' => 'EgIQAg==',
      'playlist' || 'playlists' => 'EgIQAw==',
      'all' || '' => null,
      _ => 'EgIQAQ==',
    };
  }

  Future<Map<String, dynamic>> _postInnerTube(
    Uri uri,
    Map<String, dynamic> payload, {
    required bool webClient,
  }) async {
    final response = await _client
        .post(
          uri,
          headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'Accept-Language': _youtubeLanguage,
            'User-Agent': _androidUserAgent,
            'X-YouTube-Client-Name': webClient ? '1' : '3',
            'X-YouTube-Client-Version':
                webClient ? _webClientVersion : _androidClientVersion,
          },
          body: jsonEncode(payload),
        )
        .timeout(const Duration(seconds: 10));
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw _InnerTubeHttpFailure(response.statusCode);
    }
    final decoded = jsonDecode(utf8.decode(response.bodyBytes));
    if (decoded is! Map) {
      throw const FormatException('Risposta InnerTube non valida.');
    }
    final data = Map<String, dynamic>.from(decoded);
    if (data['error'] != null) {
      throw const FormatException('InnerTube API error.');
    }
    return data;
  }

  List<SonarTubeItem> _extractNavigationItems(Map<String, dynamic> root) {
    final items = <SonarTubeItem>[];
    final seen = <String>{};

    void addVideo(Map<String, dynamic> video) {
      final id = _string(video['videoId']);
      if (id == null || seen.contains(id)) return;
      final title = _youtubeText(video['title'] ?? video['headline']);
      if (title.isEmpty) return;
      seen.add(id);
      final channel = _youtubeText(
        video['shortBylineText'] ??
            video['longBylineText'] ??
            video['ownerText'],
      );
      final published = _youtubeText(video['publishedTimeText']);
      final views = _youtubeText(
        video['viewCountText'] ?? video['shortViewCountText'],
      );
      final badgesJson = _safeJson(video['badges']).toLowerCase();
      final liveText = '$published $views'.toLowerCase();
      items.add(
        SonarTubeItem(
          kind: SonarTubeItemKind.video,
          id: id,
          title: title,
          url: Uri.https(
            'www.youtube.com',
            '/watch',
            {'v': id},
          ).toString(),
          channel: channel.isEmpty ? null : channel,
          channelId: _youtubeChannelIdFromNode(video),
          published: published.isEmpty ? null : published,
          views: views.isEmpty ? null : views,
          duration: _nullableYoutubeText(video['lengthText']),
          thumbnailUrl: _youtubeBestThumb(video['thumbnail']),
          isLive: liveText.contains('in diretta') || badgesJson.contains('live'),
        ),
      );
    }

    void addChannel(Map<String, dynamic> channel) {
      var id = _string(channel['channelId']);
      final navigation = _asMap(channel['navigationEndpoint']);
      final browseEndpoint = _asMap(navigation?['browseEndpoint']);
      id ??= _string(browseEndpoint?['browseId']);
      if (id == null || seen.contains('ch_$id')) return;
      final title = _youtubeText(channel['title']);
      if (title.isEmpty) return;
      seen.add('ch_$id');
      final canonicalBaseUrl = _string(browseEndpoint?['canonicalBaseUrl']);
      final subscriberText =
          _nullableYoutubeText(channel['subscriberCountText']);
      final subscriberTextIsHandle =
          subscriberText?.trimLeft().startsWith('@') ?? false;
      final handle = canonicalBaseUrl != null && canonicalBaseUrl.startsWith('/@')
          ? canonicalBaseUrl.substring(1)
          : subscriberTextIsHandle
              ? subscriberText
              : null;
      // Nei channelRenderer dei risultati di ricerca YouTube usa oggi
      // subscriberCountText per l'handle e videoCountText per gli iscritti.
      // Riutilizziamo videoCountText soltanto quando subscriberCountText e'
      // chiaramente un handle, cosi' non confondiamo il numero di video nei
      // normali feed/canali con il numero di iscritti.
      final subscribers = subscriberTextIsHandle
          ? _nullableYoutubeText(channel['videoCountText'])
          : subscriberText;
      items.add(
        SonarTubeItem(
          kind: SonarTubeItemKind.channel,
          id: id,
          title: title,
          channel: title,
          url: canonicalBaseUrl != null
              ? 'https://www.youtube.com$canonicalBaseUrl'
              : Uri.https(
                  'www.youtube.com',
                  '/channel/$id',
                ).toString(),
          thumbnailUrl: _youtubeBestThumb(channel['thumbnail']),
          subscribers: subscribers,
          handle: handle,
          description: _nullableYoutubeText(channel['descriptionSnippet']),
        ),
      );
    }

    void addPlaylist(Map<String, dynamic> playlist) {
      final navigation = _asMap(playlist['navigationEndpoint']);
      final watchEndpoint = _asMap(navigation?['watchEndpoint']);
      final id = _string(playlist['playlistId']) ??
          _string(watchEndpoint?['playlistId']);
      if (id == null || seen.contains('pl_$id')) return;
      final title = _youtubeText(playlist['title']);
      if (title.isEmpty) return;
      seen.add('pl_$id');
      final seed = id.startsWith('RD')
          ? _youtubeFirstVideoId(playlist)
          : null;
      items.add(
        SonarTubeItem(
          kind: SonarTubeItemKind.playlist,
          id: id,
          title: title,
          channel: _nullableYoutubeText(
            playlist['shortBylineText'] ?? playlist['longBylineText'],
          ),
          thumbnailUrl: _youtubeBestThumb(
            _firstListItem(playlist['thumbnails']) ?? playlist['thumbnail'],
          ),
          url: _playlistUrl(id, seed),
        ),
      );
    }

    void addLockup(Map<String, dynamic> lockup) {
      final contentType = _string(lockup['contentType']) ?? '';
      final isVideo = contentType == 'LOCKUP_CONTENT_TYPE_VIDEO';
      final isPlaylist = contentType == 'LOCKUP_CONTENT_TYPE_PLAYLIST' ||
          contentType == 'LOCKUP_CONTENT_TYPE_PODCAST';
      if (!isVideo && !isPlaylist) return;
      final id = _string(lockup['contentId']);
      if (id == null) return;
      final seenKey = isPlaylist ? 'pl_$id' : id;
      if (seen.contains(seenKey)) return;

      final metadata = _asMap(
        _asMap(lockup['metadata'])?['lockupMetadataViewModel'],
      );
      final contentMetadata = _asMap(
        _asMap(metadata?['metadata'])?['contentMetadataViewModel'],
      );
      final rows = _asList(contentMetadata?['metadataRows']);
      final channel = _nestedString(
        rows,
        const [0, 'metadataParts', 0, 'text', 'content'],
      );
      final views = _nestedString(
        rows,
        const [1, 'metadataParts', 0, 'text', 'content'],
      );
      final published = _nestedString(
        rows,
        const [1, 'metadataParts', 1, 'text', 'content'],
      );
      final sources = _asList(
        _asMap(
          _asMap(
            _asMap(lockup['contentImage'])?['thumbnailViewModel'],
          )?['image'],
        )?['sources'],
      );
      final lastSource = sources.isEmpty ? null : _asMap(sources.last);
      final thumbnail = _string(lastSource?['url']);
      final overlays = _asList(
        _asMap(
          _asMap(lockup['contentImage'])?['thumbnailViewModel'],
        )?['overlays'],
      );
      final firstOverlay = overlays.isEmpty ? null : _asMap(overlays.first);
      final badges = _asList(
        _asMap(
          firstOverlay?['thumbnailBottomOverlayViewModel'],
        )?['badges'],
      );
      final firstBadge = badges.isEmpty ? null : _asMap(badges.first);
      final duration = _string(
        _asMap(firstBadge?['thumbnailBadgeViewModel'])?['text'],
      );
      final title = _string(_asMap(metadata?['title'])?['content']);
      if (title == null) return;
      seen.add(seenKey);
      final seed = isPlaylist && id.startsWith('RD')
          ? _youtubeFirstVideoId(lockup)
          : null;
      items.add(
        SonarTubeItem(
          kind: isPlaylist
              ? SonarTubeItemKind.playlist
              : SonarTubeItemKind.video,
          id: id,
          title: title,
          channel: channel,
          channelId: isVideo ? _youtubeChannelIdFromNode(lockup) : null,
          published: published,
          views: views,
          duration: duration,
          thumbnailUrl: thumbnail,
          url: isPlaylist
              ? _playlistUrl(id, seed)
              : Uri.https(
                  'www.youtube.com',
                  '/watch',
                  {'v': id},
                ).toString(),
        ),
      );
    }

    void addRadio(Map<String, dynamic> radio) {
      final navigation = _asMap(radio['navigationEndpoint']);
      final watchEndpoint = _asMap(navigation?['watchEndpoint']);
      final id = _string(radio['playlistId']) ??
          _string(watchEndpoint?['playlistId']);
      if (id == null || seen.contains('pl_$id')) return;
      var seed = _string(watchEndpoint?['videoId']);
      seed ??= _youtubeFirstVideoId(radio);
      final title = _nullableYoutubeText(
            radio['title'] ?? radio['headline'],
          ) ??
          'Mix';
      seen.add('pl_$id');
      items.add(
        SonarTubeItem(
          kind: SonarTubeItemKind.playlist,
          id: id,
          title: title,
          channel: _nullableYoutubeText(
            radio['shortBylineText'] ?? radio['longBylineText'],
          ),
          thumbnailUrl: _youtubeBestThumb(radio['thumbnail']),
          url: _playlistUrl(id, seed),
        ),
      );
    }

    _walkYoutubeTree(root, (node) {
      final videoRenderer = _asMap(node['videoRenderer']);
      if (videoRenderer != null) addVideo(videoRenderer);
      final compactVideoRenderer = _asMap(node['compactVideoRenderer']);
      if (compactVideoRenderer != null) addVideo(compactVideoRenderer);
      final playlistVideoRenderer = _asMap(node['playlistVideoRenderer']);
      if (playlistVideoRenderer != null) addVideo(playlistVideoRenderer);
      final playlistPanelVideoRenderer =
          _asMap(node['playlistPanelVideoRenderer']);
      if (playlistPanelVideoRenderer != null) {
        addVideo(playlistPanelVideoRenderer);
      }
      final radioRenderer = _asMap(node['radioRenderer']);
      if (radioRenderer != null) addRadio(radioRenderer);
      final compactRadioRenderer = _asMap(node['compactRadioRenderer']);
      if (compactRadioRenderer != null) addRadio(compactRadioRenderer);
      final channelRenderer = _asMap(node['channelRenderer']);
      if (channelRenderer != null) addChannel(channelRenderer);
      final playlistRenderer = _asMap(node['playlistRenderer']);
      if (playlistRenderer != null) addPlaylist(playlistRenderer);
      final compactPlaylistRenderer = _asMap(node['compactPlaylistRenderer']);
      if (compactPlaylistRenderer != null) {
        addPlaylist(compactPlaylistRenderer);
      }
      final gridPlaylistRenderer = _asMap(node['gridPlaylistRenderer']);
      if (gridPlaylistRenderer != null) addPlaylist(gridPlaylistRenderer);
      final lockupViewModel = _asMap(node['lockupViewModel']);
      if (lockupViewModel != null) addLockup(lockupViewModel);
      final gridVideoRenderer = _asMap(node['gridVideoRenderer']);
      if (gridVideoRenderer != null) addVideo(gridVideoRenderer);
    });
    return items;
  }

  String _navigationItemKey(SonarTubeItem item) =>
      '${item.kind.name}:${item.id}';

  String _playlistUrl(String id, String? seed) {
    if (seed != null && seed.isNotEmpty) {
      return Uri.https(
        'www.youtube.com',
        '/watch',
        {'v': seed, 'list': id},
      ).toString();
    }
    return Uri.https(
      'www.youtube.com',
      '/playlist',
      {'list': id},
    ).toString();
  }

  String? _findSearchContinuation(dynamic root) {
    String? findContinuationItem(dynamic node) {
      if (node is Map) {
        final map = Map<String, dynamic>.from(node);
        final renderer = _asMap(map['continuationItemRenderer']);
        if (renderer != null) {
          final endpoint = _asMap(renderer['continuationEndpoint']);
          final command = _asMap(endpoint?['continuationCommand']);
          var token = _string(command?['token']);
          if (token == null) {
            final button = _asMap(renderer['button']);
            final buttonRenderer = _asMap(button?['buttonRenderer']);
            final buttonCommand = _asMap(buttonRenderer?['command']);
            token = _string(
              _asMap(buttonCommand?['continuationCommand'])?['token'],
            );
          }
          if (token != null) return token;
        }
        for (final child in map.values) {
          final found = findContinuationItem(child);
          if (found != null) return found;
        }
      } else if (node is List) {
        for (final child in node) {
          final found = findContinuationItem(child);
          if (found != null) return found;
        }
      }
      return null;
    }

    final preferred = findContinuationItem(root);
    if (preferred != null) return preferred;

    String? findLegacy(dynamic node) {
      if (node is Map) {
        final map = Map<String, dynamic>.from(node);
        final next = _asMap(map['nextContinuationData']);
        final token = _string(next?['continuation']);
        if (token != null) return token;
        for (final child in map.values) {
          final found = findLegacy(child);
          if (found != null) return found;
        }
      } else if (node is List) {
        for (final child in node) {
          final found = findLegacy(child);
          if (found != null) return found;
        }
      }
      return null;
    }

    return findLegacy(root);
  }

  String _youtubeText(dynamic node) {
    if (node == null) return '';
    if (node is String) return node;
    if (node is! Map) return '';
    final map = Map<String, dynamic>.from(node);
    final simpleText = map['simpleText'];
    if (simpleText is String) return simpleText;
    final runs = map['runs'];
    if (runs is List) {
      final buffer = StringBuffer();
      for (final run in runs) {
        final runMap = _asMap(run);
        final text = runMap?['text'];
        if (text != null) buffer.write(text);
      }
      return buffer.toString();
    }
    final accessibility = _asMap(map['accessibility']);
    final accessibilityData = _asMap(accessibility?['accessibilityData']);
    return _string(accessibilityData?['label']) ?? '';
  }

  String? _nullableYoutubeText(dynamic node) {
    final text = _youtubeText(node).trim();
    return text.isEmpty ? null : text;
  }

  String? _youtubeChannelIdFromNode(dynamic node) {
    if (node is Map) {
      final map = Map<String, dynamic>.from(node);
      final browseId = _string(map['browseId']);
      if (browseId != null &&
          RegExp(r'^UC[A-Za-z0-9_-]{22}$').hasMatch(browseId)) {
        return browseId;
      }
      for (final child in map.values) {
        final found = _youtubeChannelIdFromNode(child);
        if (found != null) return found;
      }
    } else if (node is List) {
      for (final child in node) {
        final found = _youtubeChannelIdFromNode(child);
        if (found != null) return found;
      }
    }
    return null;
  }

  String? _youtubeBestThumb(dynamic node) {
    final map = _asMap(node);
    if (map == null) return null;
    final thumbnails = _asList(map['thumbnails']);
    if (thumbnails.isEmpty) return null;
    final last = _asMap(thumbnails.last);
    return _string(last?['url']);
  }

  String? _youtubeFirstVideoId(dynamic node) {
    if (node is Map) {
      final map = Map<String, dynamic>.from(node);
      final videoId = _string(map['videoId']);
      if (videoId != null &&
          RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(videoId)) {
        return videoId;
      }
      for (final child in map.values) {
        final found = _youtubeFirstVideoId(child);
        if (found != null) return found;
      }
    } else if (node is List) {
      for (final child in node) {
        final found = _youtubeFirstVideoId(child);
        if (found != null) return found;
      }
    }
    return null;
  }

  void _walkYoutubeTree(
    dynamic node,
    void Function(Map<String, dynamic>) visitor,
  ) {
    if (node is Map) {
      final map = Map<String, dynamic>.from(node);
      visitor(map);
      for (final child in map.values) {
        _walkYoutubeTree(child, visitor);
      }
    } else if (node is List) {
      for (final child in node) {
        _walkYoutubeTree(child, visitor);
      }
    }
  }

  Map<String, dynamic>? _asMap(dynamic value) {
    if (value is! Map) return null;
    return Map<String, dynamic>.from(value);
  }

  List<dynamic> _asList(dynamic value) {
    return value is List ? value : const <dynamic>[];
  }

  dynamic _firstListItem(dynamic value) {
    final list = _asList(value);
    return list.isEmpty ? null : list.first;
  }

  String? _nestedString(List<dynamic> root, List<dynamic> path) {
    dynamic current = root;
    for (final segment in path) {
      if (segment is int) {
        if (current is! List ||
            segment < 0 ||
            segment >= current.length) {
          return null;
        }
        current = current[segment];
      } else if (segment is String) {
        if (current is! Map) return null;
        current = current[segment];
      } else {
        return null;
      }
    }
    return _string(current);
  }

  String _safeJson(dynamic value) {
    try {
      return jsonEncode(value);
    } catch (_) {
      return '';
    }
  }

  Future<Map<String, dynamic>> _request(
    Map<String, String> query, {
    bool allowApiError = false,
  }) async {
    final uri = endpoint.replace(
      queryParameters: {...endpoint.queryParameters, ...query},
    );
    final response = await _client.get(
      uri,
      headers: {
        'Accept': 'application/json',
        if (_clientToken.isNotEmpty) 'X-Sonarpad-Route-Token': _clientToken,
      },
    );
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw Exception('HTTP ${response.statusCode}');
    }
    final decoded = jsonDecode(utf8.decode(response.bodyBytes));
    if (decoded is! Map) {
      throw const FormatException('Risposta SonarTube non valida.');
    }
    final data = Map<String, dynamic>.from(decoded);
    if (data['ok'] != true && !allowApiError) {
      final detail = _string(data['detail']);
      final error = _string(data['error']) ?? 'Errore SonarTube';
      throw Exception(detail == null ? error : '$error: $detail');
    }
    return data;
  }

  SonarTubeItem? _parseItem(Map<String, dynamic> raw) {
    final kind = switch (_string(raw['kind'])) {
      'video' => SonarTubeItemKind.video,
      'channel' => SonarTubeItemKind.channel,
      'playlist' => SonarTubeItemKind.playlist,
      _ => null,
    };
    final id = _string(raw['id']);
    final title = _string(raw['title']);
    if (kind == null || id == null || title == null) return null;
    return SonarTubeItem(
      kind: kind,
      id: id,
      title: title,
      url: _string(raw['url']) ?? '',
      channel: _string(raw['channel']),
      channelId: _string(raw['channel_id']),
      thumbnailUrl: _string(raw['thumbnail']),
      duration: _string(raw['duration']),
      published: _string(raw['published']),
      views: _string(raw['views']),
      subscribers: _string(raw['subscribers']),
      handle: _string(raw['handle']),
      description: _string(raw['description']),
      isLive: raw['live'] == true,
    );
  }

  String? _string(dynamic value) {
    final text = value?.toString().trim();
    return text == null || text.isEmpty ? null : text;
  }

  int? _int(dynamic value) {
    if (value is int) return value;
    return int.tryParse(value?.toString() ?? '');
  }
}
