import 'dart:convert';

import 'package:http/http.dart' as http;

enum SonarTubeItemKind { video, channel, playlist }

class SonarTubeItem {
  const SonarTubeItem({
    required this.kind,
    required this.id,
    required this.title,
    required this.url,
    this.channel,
    this.channelId,
    this.thumbnailUrl,
    this.duration,
    this.published,
    this.views,
    this.description,
    this.isLive = false,
  });

  final SonarTubeItemKind kind;
  final String id;
  final String title;
  final String url;
  final String? channel;
  final String? channelId;
  final String? thumbnailUrl;
  final String? duration;
  final String? published;
  final String? views;
  final String? description;
  final bool isLive;
}

class SonarTubePage {
  const SonarTubePage({
    required this.items,
    required this.page,
    this.nextToken,
  });

  final List<SonarTubeItem> items;
  final int page;
  final String? nextToken;

  bool get hasMore => nextToken != null && nextToken!.isNotEmpty;
}

class SonarTubeResolvedMedia {
  const SonarTubeResolvedMedia({
    required this.title,
    required this.audioUrl,
    this.videoUrl,
    this.channel,
  });

  final String title;
  final String audioUrl;
  final String? videoUrl;
  final String? channel;
}


class SonarTubeComment {
  const SonarTubeComment({
    required this.id,
    required this.text,
    this.author,
    this.published,
    this.likes,
    this.authorChannelId,
    this.thumbnailUrl,
    this.replyCount = 0,
    this.pinned = false,
  });

  final String id;
  final String text;
  final String? author;
  final String? published;
  final String? likes;
  final String? authorChannelId;
  final String? thumbnailUrl;
  final int replyCount;
  final bool pinned;
}

class SonarTubeCommentsPage {
  const SonarTubeCommentsPage({
    required this.items,
    required this.page,
    this.nextToken,
  });

  final List<SonarTubeComment> items;
  final int page;
  final String? nextToken;

  bool get hasMore => nextToken != null && nextToken!.isNotEmpty;
}


class SonarTubeTranscriptUnavailableException implements Exception {
  const SonarTubeTranscriptUnavailableException();
}

class SonarTubeTranscript {
  const SonarTubeTranscript({
    required this.text,
    this.title,
    this.language,
    this.autoGenerated = false,
    this.paragraphs = const [],
  });

  final String text;
  final String? title;
  final String? language;
  final bool autoGenerated;
  final List<String> paragraphs;
}

class SonarTubeService {
  static const _compiledClientToken = String.fromEnvironment(
    'SONARPAD_ROUTE_CLIENT_TOKEN',
  );

  SonarTubeService({http.Client? client, Uri? endpoint, String? clientToken})
    : _client = client ?? http.Client(),
      endpoint =
          endpoint ?? Uri.parse('https://sonarpad.com/api/youtube_resolve.php'),
      _clientToken = clientToken ?? _compiledClientToken;

  final http.Client _client;
  final Uri endpoint;
  final String _clientToken;

  Future<SonarTubePage> search(String query, {String? token, int page = 1}) {
    return _loadPage({
      'q': query,
      'type': 'all',
      'format': 'json',
      if (token != null && token.isNotEmpty) 'token': token,
      'page': '$page',
    });
  }

  Future<SonarTubePage> browse(
    SonarTubeItem collection, {
    String? token,
    int page = 1,
  }) {
    if (collection.kind == SonarTubeItemKind.video) {
      throw ArgumentError('Un video non è una raccolta SonarTube.');
    }
    final seedVideoId = _mixSeedVideoId(collection);
    return _loadPage({
      'browse': collection.id,
      'kind': collection.kind.name,
      'title': collection.title,
      'format': 'json',
      'seed': ?seedVideoId,
      if (token != null && token.isNotEmpty) 'token': token,
      'page': '$page',
    });
  }

  String? _mixSeedVideoId(SonarTubeItem collection) {
    if (collection.kind != SonarTubeItemKind.playlist ||
        !collection.id.startsWith('RD')) {
      return null;
    }
    final uri = Uri.tryParse(collection.url);
    final seed = uri?.queryParameters['v'];
    if (seed != null && RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(seed)) {
      return seed;
    }
    if (collection.id.length == 13) {
      final derived = collection.id.substring(2);
      if (RegExp(r'^[A-Za-z0-9_-]{11}$').hasMatch(derived)) {
        return derived;
      }
    }
    return null;
  }

  Future<SonarTubeResolvedMedia> resolve(SonarTubeItem item) {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('È possibile risolvere soltanto un video.');
    }
    return resolveUrl(
      item.url.isEmpty ? item.id : item.url,
      fallbackTitle: item.title,
      fallbackChannel: item.channel,
    );
  }

  Future<SonarTubeResolvedMedia> resolveUrl(
    String url, {
    required String fallbackTitle,
    String? fallbackChannel,
  }) async {
    final trimmedUrl = url.trim();
    if (trimmedUrl.isEmpty) {
      throw ArgumentError.value(url, 'url');
    }
    final data = await _request({
      'url': trimmedUrl,
      'quality': 'best',
      'prefer': 'auto',
      'format': 'json',
    });

    final stream = _string(data['stream']);
    final streamVideo = _string(data['stream_video']);
    final streamAudio = _string(data['stream_audio']);
    if (stream == null) {
      throw const FormatException('Nessun flusso riproducibile disponibile.');
    }

    final hasSeparateStreams =
        streamVideo != null && streamAudio != null && stream == streamVideo;
    return SonarTubeResolvedMedia(
      title: _string(data['title']) ?? fallbackTitle,
      channel: _string(data['channel']) ?? fallbackChannel,
      audioUrl: hasSeparateStreams ? streamAudio : stream,
      videoUrl: hasSeparateStreams ? streamVideo : null,
    );
  }


  Future<SonarTubeItem> channelForVideo(SonarTubeItem item) async {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('video_required');
    }
    var channelId = item.channelId;
    var channelTitle = item.channel;
    if (channelId == null || channelId.isEmpty) {
      final data = await _request({
        'url': item.url.isEmpty ? item.id : item.url,
        'metadata': '1',
        'format': 'json',
      });
      channelId = _string(data['channel_id']);
      channelTitle = _string(data['channel']) ?? channelTitle;
    }
    if (channelId == null || channelId.isEmpty) {
      throw const FormatException('channel_unavailable');
    }
    return SonarTubeItem(
      kind: SonarTubeItemKind.channel,
      id: channelId,
      title: channelTitle ?? item.channel ?? item.title,
      url: Uri.https('www.youtube.com', '/channel/$channelId').toString(),
      channel: channelTitle,
    );
  }

  Future<SonarTubeCommentsPage> comments(
    SonarTubeItem item, {
    String? token,
    int page = 1,
  }) async {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('video_required');
    }
    final data = await _request({
      'url': item.url.isEmpty ? item.id : item.url,
      'comments': '1',
      'format': 'json',
      if (token != null && token.isNotEmpty) 'token': token,
      'page': '$page',
    });
    final rawItems = data['items'] is List ? data['items'] as List : const [];
    final items = rawItems
        .whereType<Map>()
        .map((raw) => Map<String, dynamic>.from(raw))
        .map((raw) {
          final id = _string(raw['id']);
          final text = _string(raw['text']);
          if (id == null || text == null) return null;
          return SonarTubeComment(
            id: id,
            text: text,
            author: _string(raw['author']),
            published: _string(raw['published']),
            likes: _string(raw['likes']),
            authorChannelId: _string(raw['author_channel_id']),
            thumbnailUrl: _string(raw['thumbnail']),
            replyCount: _int(raw['reply_count']) ?? 0,
            pinned: raw['pinned'] == true,
          );
        })
        .whereType<SonarTubeComment>()
        .toList(growable: false);
    return SonarTubeCommentsPage(
      items: items,
      page: _int(data['page']) ?? page,
      nextToken: _string(data['next_token']),
    );
  }


  Future<SonarTubeTranscript> transcribe(
    SonarTubeItem item, {
    String languageCode = 'auto',
  }) async {
    if (item.kind != SonarTubeItemKind.video) {
      throw ArgumentError('video_required');
    }
    Object? lastFailure;
    for (var attempt = 0; attempt < 2; attempt++) {
      try {
        final data = await _request(
          {
            'url': item.url.isEmpty ? item.id : item.url,
            'transcribe': '1',
            'timestamps': '1',
            'format': 'json',
            'lang': languageCode.trim().isEmpty ? 'auto' : languageCode.trim(),
          },
          allowApiError: true,
        );
        if (data['ok'] != true) {
          final error = _string(data['error']);
          if (error == 'no_captions' || error == 'no_track') {
            throw const SonarTubeTranscriptUnavailableException();
          }
          if (attempt == 0) {
            await Future<void>.delayed(const Duration(milliseconds: 250));
            continue;
          }
          if (error == 'empty_transcript') {
            throw const SonarTubeTranscriptUnavailableException();
          }
          throw Exception(error ?? 'transcript_failed');
        }
        final transcript = _string(data['transcript']);
        if (transcript == null || transcript.trim().isEmpty) {
          if (attempt == 0) {
            await Future<void>.delayed(const Duration(milliseconds: 250));
            continue;
          }
          throw const SonarTubeTranscriptUnavailableException();
        }
        final segmentTexts = (data['lines'] is List
                ? data['lines'] as List
                : const <dynamic>[])
            .whereType<Map>()
            .map((line) => _string(line['text']))
            .whereType<String>()
            .toList(growable: false);
        final plainText = segmentTexts.isEmpty
            ? transcript.trim()
            : segmentTexts.join(' ');
        return SonarTubeTranscript(
          text: plainText,
          title: _string(data['title']) ?? item.title,
          language: _string(data['lang']),
          autoGenerated: data['auto_generated'] == true,
          paragraphs: _groupTranscriptParagraphs(
            segmentTexts.isEmpty
                ? plainText.split(RegExp(r'\s+'))
                : segmentTexts,
          ),
        );
      } on SonarTubeTranscriptUnavailableException {
        rethrow;
      } catch (error) {
        lastFailure = error;
        if (attempt == 0) {
          await Future<void>.delayed(const Duration(milliseconds: 250));
          continue;
        }
      }
    }
    throw lastFailure ?? Exception('transcript_failed');
  }

  List<String> _groupTranscriptParagraphs(List<String> pieces) {
    final paragraphs = <String>[];
    final current = StringBuffer();
    for (final rawPiece in pieces) {
      final piece = rawPiece.trim().replaceAll(RegExp(r'\s+'), ' ');
      if (piece.isEmpty) continue;
      if (current.isNotEmpty) current.write(' ');
      current.write(piece);
      final text = current.toString();
      final sentenceEnd = RegExp(r'[.!?…][\"”’)]?$').hasMatch(piece);
      if ((text.length >= 220 && sentenceEnd) || text.length >= 420) {
        paragraphs.add(text);
        current.clear();
      }
    }
    if (current.isNotEmpty) paragraphs.add(current.toString());
    return paragraphs;
  }

  Future<SonarTubePage> _loadPage(Map<String, String> query) async {
    final data = await _request(query);
    final rawItems = data['items'] is List
        ? data['items'] as List
        : data['videos'] is List
        ? data['videos'] as List
        : const [];
    final items = rawItems
        .whereType<Map>()
        .map((raw) => _parseItem(Map<String, dynamic>.from(raw)))
        .whereType<SonarTubeItem>()
        .toList(growable: false);
    return SonarTubePage(
      items: items,
      page: _int(data['page']) ?? 1,
      nextToken: _string(data['next_token']),
    );
  }

  Future<Map<String, dynamic>> _request(
    Map<String, String> query, {
    bool allowApiError = false,
  }) async {
    final uri = endpoint.replace(
      queryParameters: {...endpoint.queryParameters, ...query},
    );
    final response = await _client.get(
      uri,
      headers: {
        'Accept': 'application/json',
        if (_clientToken.isNotEmpty) 'X-Sonarpad-Route-Token': _clientToken,
      },
    );
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw Exception('HTTP ${response.statusCode}');
    }
    final decoded = jsonDecode(utf8.decode(response.bodyBytes));
    if (decoded is! Map) {
      throw const FormatException('Risposta SonarTube non valida.');
    }
    final data = Map<String, dynamic>.from(decoded);
    if (data['ok'] != true && !allowApiError) {
      final detail = _string(data['detail']);
      final error = _string(data['error']) ?? 'Errore SonarTube';
      throw Exception(detail == null ? error : '$error: $detail');
    }
    return data;
  }

  SonarTubeItem? _parseItem(Map<String, dynamic> raw) {
    final kind = switch (_string(raw['kind'])) {
      'video' => SonarTubeItemKind.video,
      'channel' => SonarTubeItemKind.channel,
      'playlist' => SonarTubeItemKind.playlist,
      _ => null,
    };
    final id = _string(raw['id']);
    final title = _string(raw['title']);
    if (kind == null || id == null || title == null) return null;
    return SonarTubeItem(
      kind: kind,
      id: id,
      title: title,
      url: _string(raw['url']) ?? '',
      channel: _string(raw['channel']),
      channelId: _string(raw['channel_id']),
      thumbnailUrl: _string(raw['thumbnail']),
      duration: _string(raw['duration']),
      published: _string(raw['published']),
      views: _string(raw['views']),
      description: _string(raw['description']),
      isLive: raw['live'] == true,
    );
  }

  String? _string(dynamic value) {
    final text = value?.toString().trim();
    return text == null || text.isEmpty ? null : text;
  }

  int? _int(dynamic value) {
    if (value is int) return value;
    return int.tryParse(value?.toString() ?? '');
  }
}
