import 'news_rss_source.dart';

final ukrainianNewsSources = [
  NewsRssSource(
    name: 'Google Новини Україна',
    uri: Uri.parse('https://news.google.com/rss?hl=uk&gl=UA&ceid=UA:uk'),
    categories: [
      NewsRssCategory(name: 'Моє місто', uri: Uri.parse('https://news.google.com/'), isLocal: true),
      NewsRssCategory(name: 'Україна', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/NATION?hl=uk&gl=UA&ceid=UA:uk')),
      NewsRssCategory(name: 'Світ', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/WORLD?hl=uk&gl=UA&ceid=UA:uk')),
      NewsRssCategory(name: 'Бізнес', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/BUSINESS?hl=uk&gl=UA&ceid=UA:uk')),
      NewsRssCategory(name: 'Технології', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/TECHNOLOGY?hl=uk&gl=UA&ceid=UA:uk')),
      NewsRssCategory(name: 'Розваги', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/ENTERTAINMENT?hl=uk&gl=UA&ceid=UA:uk')),
      NewsRssCategory(name: 'Спорт', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/SPORTS?hl=uk&gl=UA&ceid=UA:uk')),
      NewsRssCategory(name: 'Здоров’я', uri: Uri.parse('https://news.google.com/news/rss/headlines/section/topic/HEALTH?hl=uk&gl=UA&ceid=UA:uk')),
    ],
  ),
  NewsRssSource(name: 'Укрінформ', uri: Uri.parse('https://www.ukrinform.ua/rss')),
  NewsRssSource(name: 'Українська правда', uri: Uri.parse('https://www.pravda.com.ua/rss/')),
  NewsRssSource(name: 'УНІАН', uri: Uri.parse('https://rss.unian.net/site/news_ukr.rss')),
  NewsRssSource(name: 'Цензор.НЕТ', uri: Uri.parse('https://censor.net/ua/rss/news')),
  NewsRssSource(name: 'NV', uri: Uri.parse('https://nv.ua/ukr/rss/all.xml')),
  NewsRssSource(name: 'Дзеркало тижня (ZN.UA)', uri: Uri.parse('https://zn.ua/ukr/rss/full.xml')),
  NewsRssSource(name: 'Економічна правда', uri: Uri.parse('https://www.epravda.com.ua/rss/')),
  NewsRssSource(name: 'ТСН', uri: Uri.parse('https://tsn.ua/rss/full.xml')),
  NewsRssSource(name: 'BBC Україна', uri: Uri.parse('https://feeds.bbci.co.uk/ukrainian/rss.xml')),
  NewsRssSource(name: 'Радіо Свобода', uri: Uri.parse('https://www.radiosvoboda.org/api/zqy-ite_iq')),
  NewsRssSource(name: 'Суспільне Новини', uri: Uri.parse('https://suspilne.media/rss/news.xml')),
  NewsRssSource(name: 'LIGA.net', uri: Uri.parse('https://news.liga.net/news/rss.xml')),
  NewsRssSource(name: 'UKR.NET', uri: Uri.parse('https://www.ukr.net/rss/news-ukrnet.rss')),
  NewsRssSource(name: '24 Канал', uri: Uri.parse('https://24tv.ua/rss/all.xml')),
  NewsRssSource(name: 'DOU', uri: Uri.parse('https://dou.ua/feed/')),
  NewsRssSource(name: 'ITC.ua', uri: Uri.parse('https://itc.ua/ua/rss')),
  NewsRssSource(name: 'Root Nation', uri: Uri.parse('https://root-nation.com/ua/feed/')),
  NewsRssSource(name: 'Gagadget', uri: Uri.parse('https://gagadget.com/uk/rss/')),
  NewsRssSource(name: 'Speka.Media', uri: Uri.parse('https://speka.media/rss')),
  NewsRssSource(name: 'Mezha.Media', uri: Uri.parse('https://mezha.media/feed/')),
  NewsRssSource(name: 'Sport.ua', uri: Uri.parse('https://sport.ua/uk/rss/all')),
  NewsRssSource(name: 'Football.ua', uri: Uri.parse('https://football.ua/rss.xml')),
  NewsRssSource(name: 'Слово про слово', uri: Uri.parse('https://slovoproslovo.info/feed/')),
];
