#!/usr/bin/env python3
"""Export the exact Sonarpad Windows pyannote segmentation result for parity tests."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

RUNTIME_ROOT = Path(__file__).resolve().parents[1]
if str(RUNTIME_ROOT) not in sys.path:
    sys.path.insert(0, str(RUNTIME_ROOT))

from audio_describer.core import speech_detector as sd  # noqa: E402


def _rle(values):
    values = list(int(v) for v in values)
    if not values:
        return []
    out = []
    current = values[0]
    length = 1
    for value in values[1:]:
        if value == current:
            length += 1
        else:
            out.append([current, length])
            current = value
            length = 1
    out.append([current, length])
    return out


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run the exact Windows Sonarpad pyannote code on a canonical mono "
            "16 kHz PCM16 WAV and export a JSON reference."
        )
    )
    parser.add_argument("wav", help="Canonical WAV generated by the mobile parity test")
    parser.add_argument(
        "output",
        nargs="?",
        help="Output JSON path (default: <wav>.windows.json)",
    )
    args = parser.parse_args()

    wav_path = Path(args.wav).expanduser().resolve()
    if not wav_path.is_file():
        parser.error(f"WAV not found: {wav_path}")
    output_path = (
        Path(args.output).expanduser().resolve()
        if args.output
        else wav_path.with_suffix(wav_path.suffix + ".windows.json")
    )

    model_path_str = sd.get_bundled_model_path()
    if not model_path_str:
        raise SystemExit("Bundled pyannote model not found in the Windows source/runtime.")
    model_path = Path(model_path_str)

    messages = []
    session = sd._get_onnx_session(messages.append)
    samples, sample_rate = sd._load_pcm16_waveform(str(wav_path))
    if sample_rate != sd.SEGMENTATION_SAMPLE_RATE:
        raise SystemExit(
            f"Unexpected sample rate {sample_rate}; expected {sd.SEGMENTATION_SAMPLE_RATE}."
        )
    duration_sec = len(samples) / sample_rate if sample_rate else 0.0

    chunk_counts = sd._run_onnx_segmentation(session, samples, sample_rate)
    frame_counts = sd._aggregate_segmentation_counts(chunk_counts)
    raw_intervals = sd._counts_to_intervals(frame_counts)
    protected_intervals = sd.merge_intervals(
        raw_intervals,
        padding_sec=sd.DEFAULT_PADDING_SEC,
        duration_sec=duration_sec,
    )
    protected_seconds = sum(end - start for start, end in protected_intervals)

    frame_bytes = np.asarray(frame_counts, dtype=np.uint8).tobytes()
    ort_version = getattr(sys.modules.get("onnxruntime"), "__version__", None)
    if not ort_version:
        try:
            import onnxruntime as ort  # noqa: WPS433

            ort_version = ort.__version__
        except Exception:
            ort_version = "unknown"

    payload = {
        "schema": "sonarpad_pyannote_parity_v1",
        "platform": "windows",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_file": wav_path.name,
        "canonical_wav_file": wav_path.name,
        "limit_seconds": None,
        "model": {
            "name": "pyannote Community-1 segmentation ONNX",
            "revision": sd.BUNDLED_MODEL_REVISION,
            "sha256": _sha256_file(model_path),
        },
        "runtime": {
            "onnxruntime_version": ort_version,
            "provider": "CPUExecutionProvider",
            "intra_op_threads": max(1, min(4, os.cpu_count() or 1)),
            "batch_size": sd.SEGMENTATION_BATCH_SIZE,
            "input_name": session.get_inputs()[0].name,
            "output_names": [item.name for item in session.get_outputs()],
        },
        "audio": {
            "sample_rate": sample_rate,
            "sample_count": len(samples),
            "duration_seconds": duration_sec,
        },
        "parameters": {
            "window_seconds": sd.SEGMENTATION_WINDOW_SEC,
            "step_seconds": sd.SEGMENTATION_STEP_SEC,
            "frame_duration_seconds": sd.SEGMENTATION_FRAME_DURATION_SEC,
            "frame_step_seconds": sd.SEGMENTATION_FRAME_STEP_SEC,
            "padding_seconds": sd.DEFAULT_PADDING_SEC,
        },
        "analysis": {
            "chunk_count": int(len(chunk_counts)),
            "frame_count": int(len(frame_counts)),
            "frame_counts_sha256": hashlib.sha256(frame_bytes).hexdigest(),
            "frame_counts_rle": _rle(frame_counts),
            "raw_intervals": [[float(a), float(b)] for a, b in raw_intervals],
            "protected_intervals": [
                [float(a), float(b)] for a, b in protected_intervals
            ],
            "protected_seconds": float(protected_seconds),
            "protected_percent": (
                float(protected_seconds / duration_sec * 100.0)
                if duration_sec
                else 0.0
            ),
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Windows reference written to: {output_path}")
    print(f"Model SHA-256: {payload['model']['sha256']}")
    print(f"Frame-count SHA-256: {payload['analysis']['frame_counts_sha256']}")
    print(f"Protected intervals: {len(protected_intervals)}")
    print(f"Protected seconds: {protected_seconds:.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
