// AUTO-GENERATED — non modificare manualmente.
// Generato da scripts/scrape_saints.py
//
// Strategia:
//   IT  -> santodelgiorno.it (fonte autorevole italiana)
//   EN/FR/ES -> Wikipedia interwiki della pagina IT
//              (stessa persona, nome ufficiale nella lingua)

const Map<String, Map<String, String>> kSaintsData = {
  "1-1": {
    "it": "Maria Santissima Madre di Dio",
    "en": "Solemnity of Mary, Mother of God",
    "fr": "Marie, Mère de Dieu",
    "es": "Solemnidad de Santa María, Madre de Dios",
  },
  "2-1": {
    "it": "Santi Basilio Magno e Gregorio Nazianzeno",
    "en": "Gregory of Nazianzus",
    "fr": "Grégoire de Nazianze",
    "es": "Gregorio Nacianceno",
  },
  "3-1": {
    "it": "Santissimo Nome di Gesù",
    "en": "Feast of the Holy Name of Jesus",
    "fr": "Très Saint Nom de Jésus",
    "es": "Fiesta del Santísimo Nombre de Jesús",
  },
  "4-1": {
    "it": "Sant'Angela da Foligno",
    "en": "Angela of Foligno",
    "fr": "Angèle de Foligno",
    "es": "Ángela de Foligno",
  },
  "5-1": {
    "it": "Sant' Amelia",
    "en": "Diocese of Terni-Narni-Amelia",
    "fr": "Diocèse de Terni-Narni-Amelia",
    "es": "Diócesis de Terni-Narni-Amelia",
  },
  "6-1": {
    "it": "Epifania del Signore",
    "en": "Epiphany",
    "fr": "Épiphanie",
    "es": "Epifanía",
  },
  "7-1": {
    "it": "San Raimondo de Penafort",
    "en": "Raymond of Peñafort",
    "fr": "Raymond de Peñafort",
    "es": "Raimundo de Peñafort",
  },
  "8-1": {
    "it": "San Massimo di Pavia",
    "en": "University of Pavia",
    "fr": "Université de Pavie",
    "es": "Universidad de Pavía",
  },
  "9-1": {
    "it": "San Marcellino di Ancona",
    "en": "Marcellinus of Ancona",
    "fr": "Marcellin d'Ancône",
    "es": "Marcelino de Ancona",
  },
  "10-1": {
    "it": "Sant' Aldo",
    "en": "Saint Aldo",
    "fr": "Saint Aldric",
    "es": "San Aldo",
  },
  "11-1": {
    "it": "Battesimo di Gesù",
    "en": "Baptism of the Lord",
    "fr": "Baptême du Seigneur",
    "es": "Bautismo del Señor",
  },
  "12-1": {
    "it": "San Bernardo da Corleone",
    "en": "Bernard of Corleone",
    "fr": "Bernard de Corleone",
    "es": "Bernardo de Corleone",
  },
  "13-1": {
    "it": "Sant' Ilario di Poitiers",
    "en": "Hilary of Poitiers",
    "fr": "Hilaire de Poitiers",
    "es": "Hilario de Poitiers",
  },
  "14-1": {
    "it": "San Felice da Nola",
    "en": "Felix of Nola",
    "fr": "Félix de Nole",
    "es": "Félix de Nola",
  },
  "15-1": {
    "it": "San Mauro",
    "en": "San Mauro Castelverde",
    "fr": "San Mauro Castelverde",
    "es": "San Mauro Castelverde",
  },
  "16-1": {
    "it": "San Marcello I",
    "en": "Pope Marcellus I",
    "fr": "Marcel Ier",
    "es": "Marcelo I",
  },
  "17-1": {
    "it": "Sant' Antonio",
    "en": "Anthony of Padua",
    "fr": "Antoine de Padoue",
    "es": "Antonio de Padua",
  },
  "18-1": {
    "it": "Santa Margherita d'Ungheria",
    "en": "Margaret of Bohemia, Queen of Hungary",
    "fr": "Marguerite de Luxembourg",
    "es": "Margarita de Luxemburgo",
  },
  "19-1": {
    "it": "Santi Mario, Marta, Abaco e Audiface",
    "en": "Marius, Martha, Audifax, and Abachum",
    "fr": "Maris, Marthe, Audifax et Abacum",
    "es": "Mario, Marta, Audifax y Ábaco",
  },
  "20-1": {
    "it": "Santi Sebastiano e Fabiano",
    "en": "Sebastian of Milan",
    "fr": "Sébastien de Milan",
    "es": "Sebastián de Milán",
  },
  "21-1": {
    "it": "Sant' Agnese",
    "en": "Agnes of France",
    "fr": "Agnès de France",
    "es": "Inés de Francia",
  },
  "22-1": {
    "it": "San Vincenzo di Saragozza",
    "en": "Vincent of Saragossa",
    "fr": "Vincent de Saragosse",
    "es": "Vicente de Huesca",
  },
  "23-1": {
    "it": "Sposalizio di Maria e Giuseppe",
    "en": "Marriage of the Virgin",
    "fr": "Mariage de la Vierge",
    "es": "Los desposorios de la Virgen",
  },
  "24-1": {
    "it": "San Francesco di Sales",
    "en": "Francis de Sales",
    "fr": "François de Sales",
    "es": "Francisco de Sales",
  },
  "25-1": {
    "it": "Conversione di San Paolo Apostolo",
    "en": "Conversion of Paul the Apostle",
    "fr": "Conversion de Paul de Tarse",
    "es": "Conversión de Pablo de Tarso",
  },
  "26-1": {
    "it": "Santi Timoteo e Tito",
    "en": "Saint Timothy",
    "fr": "Timothée (Nouveau Testament)",
    "es": "Timoteo de Éfeso",
  },
  "27-1": {
    "it": "Sant' Angela Merici",
    "en": "Angela Merici",
    "fr": "Angèle Mérici",
    "es": "Ángela de Mérici",
  },
  "28-1": {
    "it": "San Tommaso d'Aquino",
    "en": "Thomas Aquinas",
    "fr": "Thomas d'Aquin",
    "es": "Tomás de Aquino",
  },
  "29-1": {
    "it": "San Costanzo di Perugia",
    "en": "Constantius of Perugia",
    "fr": "Constance de Pérouse",
    "es": "Constancio de Perugia",
  },
  "30-1": {
    "it": "Santa Martina",
    "en": "Martina of Rome",
    "fr": "Martina Navrátilová",
    "es": "Martina Navrátilová",
  },
  "31-1": {
    "it": "San Giovanni Bosco",
    "en": "John Bosco",
    "fr": "Salésiens",
    "es": "Pía Sociedad de San Francisco de Sales",
  },
  "1-2": {
    "it": "Santa Brigida d'Irlanda",
    "en": "Brigid of Kildare",
    "fr": "Brigitte d'Irlande",
    "es": "Brígida de Kildare",
  },
  "2-2": {
    "it": "Presentazione del Signore",
    "en": "Candlemas",
    "fr": "Présentation de Jésus au Temple",
    "es": "Candelaria",
  },
  "3-2": {
    "it": "San Biagio",
    "en": "Saint Blaise",
    "fr": "Blaise de Sébaste",
    "es": "Blas de Sebaste",
  },
  "4-2": {
    "it": "San Giuseppe da Leonessa",
    "en": "Joseph of Leonessa",
    "fr": "Joseph de Leonessa",
    "es": "José de Leonisa",
  },
  "5-2": {
    "it": "Sant' Agata",
    "en": "Agatha of Sicily",
    "fr": "Agathe de Catane",
    "es": "Águeda de Catania",
  },
  "6-2": {
    "it": "San Paolo Miki e compagni",
    "en": "Paul Miki",
    "fr": "Paul Miki",
    "es": "Pablo Miki",
  },
  "7-2": {
    "it": "San Riccardo",
    "en": "Richard of Andria",
    "fr": "Richard d'Andria",
    "es": "Ricardo de Andria",
  },
  "8-2": {
    "it": "San Girolamo Emiliani",
    "en": "Jerome Emiliani",
    "fr": "Jérôme Émilien",
    "es": "Jerónimo Emiliani",
  },
  "9-2": {
    "it": "Sant' Apollonia",
    "en": "Apollonius the Apologist",
    "fr": "Apolline d'Alexandrie",
    "es": "Apolonio de Alejandría",
  },
  "10-2": {
    "it": "Santa Scolastica",
    "en": "Scholastica of Nursia",
    "fr": "Scholastique de Nursie",
    "es": "Escolástica de Nursia",
  },
  "11-2": {
    "it": "Beata Vergine Maria di Lourdes",
    "en": "Our Lady of Lourdes",
    "fr": "Notre-Dame de Lourdes",
    "es": "Nuestra Señora de Lourdes",
  },
  "12-2": {
    "it": "Santi Martiri di Abitina",
    "en": "Martyrs of Abitinae",
    "fr": "Martyrs d'Abitène",
    "es": "Mártires de Abitinia",
  },
  "13-2": {
    "it": "Sante Fosca e Maura",
    "en": "Fusca of Ravenna",
    "fr": "Fosca et Maure",
    "es": "Fosca y Maura",
  },
  "14-2": {
    "it": "San Valentino",
    "en": "Saint Valentine",
    "fr": "Valentin de Terni",
    "es": "Valentín de Roma",
  },
  "15-2": {
    "it": "Santi Faustino e Giovita",
    "en": "Faustinus and Jovita",
    "fr": "Faustin et Jovite",
    "es": "Faustino y Jovita",
  },
  "16-2": {
    "it": "Santa Giuliana di Nicomedia",
    "en": "Juliana of Nicomedia",
    "fr": "Julienne de Nicomédie",
    "es": "Juliana de Nicomedia",
  },
  "17-2": {
    "it": "Santi Sette Fondatori dell'Ordine dei Servi di Maria",
    "en": "Servite Order",
    "fr": "Ordre des Servites de Marie",
    "es": "Orden de los Servitas",
  },
  "18-2": {
    "it": "Sacre Ceneri",
    "en": "Ash Wednesday",
    "fr": "Mercredi des Cendres",
    "es": "Miércoles de Ceniza",
  },
  "19-2": {
    "it": "San Corrado Confalonieri",
    "en": "Conrad of Piacenza",
    "fr": "Conrad de Plaisance",
    "es": "Conrado de Piacenza",
  },
  "20-2": {
    "it": "Santa Giacinta Marto",
    "en": "Jacinta Marto",
    "fr": "Jacinthe Marto",
    "es": "Jacinta Marto",
  },
  "21-2": {
    "it": "Sant' Eleonora",
    "en": "Eleanor of Provence",
    "fr": "Éléonore de Provence",
    "es": "Leonor de Provenza",
  },
  "22-2": {
    "it": "Cattedra di San Pietro Apostolo",
    "en": "Chair of Saint Peter",
    "fr": "Chaire de saint Pierre",
    "es": "Cátedra de San Pedro",
  },
  "23-2": {
    "it": "San Policarpo",
    "en": "Polycarp",
    "fr": "Polycarpe de Smyrne",
    "es": "Policarpo de Esmirna",
  },
  "24-2": {
    "it": "Sant' Etelberto",
    "en": "Saint Ethelbert of Kent",
    "fr": "Éthelbert de Kent",
    "es": "Etelberto de Kent",
  },
  "25-2": {
    "it": "San Gerlando di Agrigento",
    "en": "Gerland of Agrigento",
    "fr": "Gerland d'Agrigente",
    "es": "Gerlando de Agrigento",
  },
  "26-2": {
    "it": "Sant' Alessandro di Alessandria",
    "en": "Pope Alexander I of Alexandria",
    "fr": "Alexandre d'Alexandrie",
    "es": "Alejandro de Alejandría",
  },
  "27-2": {
    "it": "San Gabriele dell'Addolorata",
    "en": "St. Gabriel's shrine",
    "fr": "Sanctuaire Saint Gabriel dell'Addolorata",
    "es": "Gabriel de la Dolorosa",
  },
  "28-2": {
    "it": "San Romano di Condat",
    "en": "Romanus of Condat",
    "fr": "Romain de Condat",
    "es": "Román de Condat",
  },
  "1-3": {
    "it": "Sant' Albino di Angers",
    "en": "Albinus of Angers",
    "fr": "Aubin d'Angers",
    "es": "Albino de Angers",
  },
  "2-3": {
    "it": "Sant' Agnese di Boemia",
    "en": "Agnes of Bohemia",
    "fr": "Agnès de Bohême",
    "es": "Inés de Bohemia",
  },
  "3-3": {
    "it": "Santa Cunegonda",
    "en": "Cunigunde of Luxembourg",
    "fr": "Cunégonde de Luxembourg",
    "es": "Cunegunda de Luxemburgo",
  },
  "4-3": {
    "it": "San Casimiro",
    "en": "Saint Casimir",
    "fr": "Saint Casimir",
    "es": "Casimiro el Santo",
  },
  "5-3": {
    "it": "Sant' Adriano di Cesarea",
    "en": "Adrian of Batanea",
    "fr": "Adrien de Césarée",
    "es": "Adriano de Cesarea",
  },
  "6-3": {
    "it": "Santa Rosa da Viterbo",
    "en": "Santa Rosa de Viterbo",
    "fr": "Santa Rosa de Viterbo",
    "es": "Santa Rosa de Viterbo",
  },
  "7-3": {
    "it": "Sante Perpetua e Felicita",
    "en": "Perpetua and Felicity",
    "fr": "Perpétue et Félicité",
    "es": "Perpetua y Felicidad",
  },
  "8-3": {
    "it": "San Giovanni di Dio",
    "en": "John of God",
    "fr": "Jean de Dieu",
    "es": "Juan de Dios",
  },
  "9-3": {
    "it": "Santa Francesca Romana",
    "en": "Francesca Romana Coluzzi",
    "fr": "Francesca Romana Coluzzi",
    "es": "Francisca Romana",
  },
  "10-3": {
    "it": "San Macario di Gerusalemme",
    "en": "Macarius of Jerusalem",
    "fr": "Macaire de Jérusalem",
    "es": "Macario I de Jerusalén",
  },
  "11-3": {
    "it": "San Costantino",
    "en": "Constantine of Murom",
    "fr": "Constantin d'Écosse",
    "es": "Constantino de Escocia",
  },
  "12-3": {
    "it": "San Luigi Orione",
    "en": "Luigi Orione",
    "fr": "Louis Orione",
    "es": "Luis Orione",
  },
  "13-3": {
    "it": "San Rodrigo di Cordova",
    "en": "Saint Roderick",
    "fr": "Rodrigue de Cordoue",
    "es": "Rodrigo de Córdoba",
  },
  "14-3": {
    "it": "Santa Matilde di Germania",
    "en": "Matilda of Germany, Countess Palatine of Lotharingia",
    "fr": "Mathilde de Germanie",
    "es": "Matilde de Alemania",
  },
  "15-3": {
    "it": "Santa Luisa de Marillac",
    "en": "Louise de Marillac",
    "fr": "Louise de Marillac",
    "es": "Luisa de Marillac",
  },
  "16-3": {
    "it": "Sant' Eriberto di Colonia",
    "en": "Heribert of Cologne",
    "fr": "Héribert de Cologne",
    "es": "Heriberto de Colonia",
  },
  "17-3": {
    "it": "San Patrizio",
    "en": "Saint Patrick",
    "fr": "Puits de saint Patrice",
    "es": "San Patricio",
  },
  "18-3": {
    "it": "San Cirillo di Gerusalemme",
    "en": "Cyril of Jerusalem",
    "fr": "Cyrille de Jérusalem",
    "es": "Cirilo de Jerusalén",
  },
  "19-3": {
    "it": "San Giuseppe",
    "en": "Saint Joseph",
    "fr": "Joseph (Nouveau Testament)",
    "es": "José de Nazaret",
  },
  "20-3": {
    "it": "Sant' Alessandra di Amiso e compagne",
    "en": "Alexandra of Amiso",
    "fr": "Alexandra d'Amisos",
    "es": "Alejandra de Amiso",
  },
  "21-3": {
    "it": "San Serapione di Thmuis",
    "en": "Serapion of Thmuis",
    "fr": "Sérapion de Thmuis",
    "es": "Serapión de Thmuis",
  },
  "22-3": {
    "it": "Santa Lea di Roma",
    "en": "Saint Lea",
    "fr": "Sainte Léa",
    "es": "Lea de Roma",
  },
  "23-3": {
    "it": "San Turibio de Mogrovejo",
    "en": "Turibius of Mogrovejo",
    "fr": "Turibe de Mogrovejo",
    "es": "Toribio de Mogrovejo",
  },
  "24-3": {
    "it": "Santa Caterina di Svezia",
    "en": "Catherine of Vadstena",
    "fr": "Catherine de Suède",
    "es": "Catalina de Vadstena",
  },
  "25-3": {
    "it": "Annunciazione del Signore",
    "en": "Annunciation of the Lord",
    "fr": "Annonciation du Seigneur",
    "es": "Anunciación del Señor",
  },
  "26-3": {
    "it": "Sant' Emanuele",
    "en": "Victor Emmanuel II",
    "fr": "Victor-Emmanuel II",
    "es": "Víctor Manuel II de Italia",
  },
  "27-3": {
    "it": "San Ruperto",
    "en": "Rupert of Bingen",
    "fr": "Rupert de Salzbourg",
    "es": "Ruperto de Bingen",
  },
  "28-3": {
    "it": "Santo Stefano Harding",
    "en": "Stephen Harding",
    "fr": "Étienne Harding",
    "es": "Esteban Harding",
  },
  "29-3": {
    "it": "Domenica delle Palme",
    "en": "Palm Sunday",
    "fr": "Dimanche des Rameaux",
    "es": "Domingo de Ramos",
  },
  "30-3": {
    "it": "Beato Amedeo IX di Savoia",
    "en": "Amadeus IX, Duke of Savoy",
    "fr": "Amédée IX",
    "es": "Amadeo IX de Saboya",
  },
  "31-3": {
    "it": "San Beniamino",
    "en": "Benjamin the Deacon",
    "fr": "Benjamin le Diacre",
    "es": "Benjamín el Diácono",
  },
  "1-4": {
    "it": "Sant' Ugo di Grenoble",
    "en": "Hugh of Châteauneuf",
    "fr": "Hugues de Grenoble",
    "es": "Hugo de Grenoble",
  },
  "2-4": {
    "it": "Giovedì Santo",
    "en": "Maundy Thursday",
    "fr": "Jeudi saint",
    "es": "Jueves Santo",
  },
  "3-4": {
    "it": "Venerdì Santo",
    "en": "Good Friday",
    "fr": "Vendredi saint",
    "es": "Viernes Santo",
  },
  "4-4": {
    "it": "Sabato Santo",
    "en": "Holy Saturday",
    "fr": "Samedi saint",
    "es": "Sábado Santo",
  },
  "5-4": {
    "it": "Domenica di Pasqua",
    "en": "Fifth Sunday of Easter",
    "fr": "Dimanche de Pâques",
    "es": "Domingo de Resurrección",
  },
  "6-4": {
    "it": "San Pietro da Verona",
    "en": "Peter of Verona",
    "fr": "Pierre de Vérone",
    "es": "Pedro de Verona",
  },
  "7-4": {
    "it": "San Giovanni Battista de La Salle",
    "en": "Jean-Baptiste de La Salle",
    "fr": "Jean-Baptiste de La Salle",
    "es": "Juan Bautista de La Salle",
  },
  "8-4": {
    "it": "San Dionigi di Corinto",
    "en": "Dionysius of Corinth",
    "fr": "Denys de Corinthe",
    "es": "Dionisio de Corinto",
  },
  "9-4": {
    "it": "San Demetrio di Tessalonica",
    "en": "Demetrius of Thessaloniki",
    "fr": "Démétrios de Thessalonique",
    "es": "Demetrio de Tesalónica",
  },
  "10-4": {
    "it": "Santa Maddalena di Canossa",
    "en": "Magdalene of Canossa",
    "fr": "Madeleine de Canossa",
    "es": "Magdalena de Canossa",
  },
  "11-4": {
    "it": "Santa Gemma Galgani",
    "en": "Sanctuary of Santa Gemma, Lucca",
    "fr": "Gemma Galgani",
    "es": "Gema Galgani",
  },
  "12-4": {
    "it": "Domenica della Divina Misericordia",
    "en": "Divine Mercy Sunday",
    "fr": "Dimanche de la divine Miséricorde",
    "es": "Domingo de la Divina Misericordia",
  },
  "13-4": {
    "it": "San Martino I",
    "en": "Pope Martin I",
    "fr": "Martin Ier",
    "es": "Martín I",
  },
  "14-4": {
    "it": "Santa Liduina",
    "en": "Lidwina",
    "fr": "Lidwine de Schiedam",
    "es": "Lidwina",
  },
  "15-4": {
    "it": "San Damiano de Veuster",
    "en": "Father Damien",
    "fr": "Père Damien",
    "es": "Damián de Molokai",
  },
  "16-4": {
    "it": "Santa Bernardetta Soubirous",
    "en": "Bernadette Soubirous",
    "fr": "Bernadette Soubirous",
    "es": "Bernadette Soubirous",
  },
  "17-4": {
    "it": "San Roberto di La Chaise-Dieu",
    "en": "Robert de Turlande",
    "fr": "Robert de Turlande",
    "es": "Roberto de Chaise-Dieu",
  },
  "18-4": {
    "it": "San Galdino",
    "en": "Galdinus of Milan",
    "fr": "Galdino de Milan",
    "es": "Galdino de Milán",
  },
  "19-4": {
    "it": "Sant' Emma di Sassonia",
    "en": "Emma of Lesum",
    "fr": "Emma de Saxe",
    "es": "Emma de Sajonia",
  },
  "20-4": {
    "it": "Santa Sara di Antiochia",
    "en": "Sarah of Antioch",
    "fr": "Sara d'Antioche",
    "es": "Sara de Antioquía",
  },
  "21-4": {
    "it": "Sant' Anselmo d'Aosta",
    "en": "Anselm of Canterbury",
    "fr": "Anselme de Cantorbéry",
    "es": "Anselmo de Canterbury",
  },
  "22-4": {
    "it": "San Leonida di Alessandria",
    "en": "Leonidas of Alexandria",
    "fr": "Léonide d'Alexandrie",
    "es": "Leónidas de Alejandría (poeta)",
  },
  "23-4": {
    "it": "San Giorgio",
    "en": "Saint George's Cross",
    "fr": "Croix de saint Georges",
    "es": "Cruz de San Jorge",
  },
  "24-4": {
    "it": "San Fedele da Sigmaringen",
    "en": "Fidelis of Sigmaringen",
    "fr": "Fidèle de Sigmaringen",
    "es": "Fidel de Sigmaringa",
  },
  "25-4": {
    "it": "San Marco",
    "en": "Finding of the Body of Saint Mark",
    "fr": "La Découverte du corps de saint Marc",
    "es": "Marcos el Evangelista",
  },
  "26-4": {
    "it": "Madonna del Buon Consiglio",
    "en": "Our Lady of Good Counsel",
    "fr": "Notre-Dame du Bon Conseil",
    "es": "Nuestra Señora del Buen Consejo",
  },
  "27-4": {
    "it": "Santa Zita",
    "en": "Zita of Bourbon-Parma",
    "fr": "Zita de Bourbon-Parme",
    "es": "Zita de Borbón-Parma",
  },
  "28-4": {
    "it": "Santa Valeria di Milano",
    "en": "Valeria of Milan",
    "fr": "Valérie de Milan",
    "es": "Valeria de Milán",
  },
  "29-4": {
    "it": "Santa Caterina da Siena",
    "en": "Laura Montoya",
    "fr": "Laura Montoya",
    "es": "Laura Montoya",
  },
  "30-4": {
    "it": "San Pio V",
    "en": "Pope Pius V",
    "fr": "Pie V",
    "es": "Pío V",
  },
  "1-5": {
    "it": "San Giuseppe",
    "en": "Saint Joseph",
    "fr": "Joseph (Nouveau Testament)",
    "es": "José de Nazaret",
  },
  "2-5": {
    "it": "Sant' Atanasio",
    "en": "Athanasius of Alexandria",
    "fr": "Athanase d'Alexandrie",
    "es": "Atanasio de Alejandría",
  },
  "3-5": {
    "it": "Santi Filippo e Giacomo",
    "en": "Sorrento Cathedral",
    "fr": "Cathédrale de Sorrente",
    "es": "Felipe y Santiago Apóstoles",
  },
  "4-5": {
    "it": "San Ciriaco di Gerusalemme",
    "en": "Judas Cyriacus",
    "fr": "Cyriaque de Jérusalem",
    "es": "Ciriaco de Jerusalén",
  },
  "5-5": {
    "it": "Sant' Angelo da Gerusalemme",
    "en": "Angelus of Jerusalem",
    "fr": "Ange de Jérusalem",
    "es": "Ángel de Sicilia",
  },
  "6-5": {
    "it": "San Pietro Nolasco",
    "en": "Peter Nolasco",
    "fr": "Pierre Nolasque",
    "es": "Pedro Nolasco",
  },
  "7-5": {
    "it": "Santa Flavia Domitilla",
    "en": "Flavia Domitilla (wife of Clemens)",
    "fr": "Flavia Domitilla",
    "es": "Flavia Domitila",
  },
  "8-5": {
    "it": "Madonna del Rosario di Pompei",
    "en": "Our Lady of the Rosary of Pompei",
    "fr": "Notre-Dame du Rosaire de Pompéi",
    "es": "Nuestra Señora del Rosario de Pompeya",
  },
  "9-5": {
    "it": "Sant'Isaia",
    "en": "Book of Isaiah",
    "fr": "Livre d'Isaïe",
    "es": "Libro de Isaías",
  },
  "10-5": {
    "it": "San Cataldo di Rachau",
    "en": "Catald",
    "fr": "Catalde de Tarente",
    "es": "Cataldo de Tarento",
  },
  "11-5": {
    "it": "Sant' Ignazio da Laconi",
    "en": "Ignatius of Laconi",
    "fr": "Ignace de Laconi",
    "es": "Ignacio de Láconi",
  },
  "12-5": {
    "it": "Santi Nereo e Achilleo",
    "en": "Nereus and Achilleus",
    "fr": "Nérée et Achillée",
    "es": "Nereo y Aquileo",
  },
  "13-5": {
    "it": "Beata Vergine Maria di Fatima",
    "en": "Mary, mother of Jesus",
    "fr": "Marie (mère de Jésus)",
    "es": "María (madre de Jesús)",
  },
  "14-5": {
    "it": "San Mattia",
    "en": "Matthias the Apostle",
    "fr": "Matthias (apôtre)",
    "es": "Matías el Apóstol",
  },
  "15-5": {
    "it": "Sant' Isidoro l'agricoltore",
    "en": "Isidore the Laborer",
    "fr": "Isidore le Laboureur",
    "es": "Isidro Labrador",
  },
  "16-5": {
    "it": "Sant' Ubaldo di Gubbio",
    "en": "Ubald",
    "fr": "Ubald Baldassini",
    "es": "Ubaldo de Gubbio",
  },
  "17-5": {
    "it": "Ascensione di Gesù",
    "en": "Ascension of Jesus",
    "fr": "Ascension du Seigneur",
    "es": "Ascensión de Jesús",
  },
  "18-5": {
    "it": "San Giovanni I",
    "en": "John I",
    "fr": "Jean Ier",
    "es": "Juan I",
  },
  "19-5": {
    "it": "San Celestino V",
    "en": "Pope Celestine V",
    "fr": "Célestin V",
    "es": "Celestino V",
  },
  "20-5": {
    "it": "San Bernardino da Siena",
    "en": "Bernardino of Siena",
    "fr": "Bernardin de Sienne",
    "es": "Bernardino de Siena",
  },
  "21-5": {
    "it": "San Vittorio di Cesarea",
    "en": "Victor of Caesarea",
    "fr": "Victor de Césarée",
    "es": "Víctor de Cesarea",
  },
  "22-5": {
    "it": "Santa Rita da Cascia",
    "en": "Rita of Cascia",
    "fr": "Rita de Cascia",
    "es": "Rita de Casia",
  },
  "23-5": {
    "it": "San Desiderio di Langres",
    "en": "Desiderius of Langres",
    "fr": "Didier de Langres",
    "es": "Desiderio de Langres",
  },
  "24-5": {
    "it": "Pentecoste",
    "en": "Pentecost",
    "fr": "Pentecôte",
    "es": "Pentecostés (Tiziano)",
  },
  "25-5": {
    "it": "Maria Madre della Chiesa",
    "en": "Mary, mother of Jesus",
    "fr": "Marie (mère de Jésus)",
    "es": "María (madre de Jesús)",
  },
  "26-5": {
    "it": "San Filippo Neri",
    "en": "Oratory of Saint Philip Neri",
    "fr": "Congrégation de l'Oratoire",
    "es": "Congregación del Oratorio de San Felipe Neri",
  },
  "27-5": {
    "it": "Sant' Agostino di Canterbury",
    "en": "Augustine of Canterbury",
    "fr": "Augustin de Cantorbéry",
    "es": "Agustín de Canterbury",
  },
  "28-5": {
    "it": "San Germano di Parigi",
    "en": "Germain of Paris",
    "fr": "Germain de Paris",
    "es": "Germán de París",
  },
  "29-5": {
    "it": "San Paolo VI",
    "en": "Pope Paul VI",
    "fr": "Paul VI",
    "es": "Pablo VI",
  },
  "30-5": {
    "it": "Santa Giovanna d'Arco",
    "en": "The Trial of Joan of Arc",
    "fr": "Procès de Jeanne d'Arc (film)",
    "es": "El proceso de Juana de Arco",
  },
  "31-5": {
    "it": "Santissima Trinità",
    "en": "Trinity Sunday",
    "fr": "Trinité",
    "es": "Santísima Trinidad",
  },
  "1-6": {
    "it": "San Giustino",
    "en": "Justin of Chieti",
    "fr": "Justin de Naplouse",
    "es": "Justino de Chieti",
  },
  "2-6": {
    "it": "Santi Marcellino e Pietro",
    "en": "Marcellinus and Peter",
    "fr": "Marcellin et Pierre",
    "es": "Marcelino y Pedro",
  },
  "3-6": {
    "it": "Santi Carlo Lwanga e 12 compagni",
    "en": "Charles Lwanga and Companions",
    "fr": "Charles Lwanga et compagnons",
    "es": "Carlos Lwanga y compañeros",
  },
  "4-6": {
    "it": "San Francesco Caracciolo",
    "en": "Francesco Caracciolo (naval officer)",
    "fr": "Francesco Caracciolo (amiral)",
    "es": "Francesco Caracciolo",
  },
  "5-6": {
    "it": "San Bonifacio",
    "en": "Boniface of Tarsus",
    "fr": "Boniface de Mayence",
    "es": "Bonifacio de Tarso",
  },
  "6-6": {
    "it": "San Norberto",
    "en": "Norbert of Xanten",
    "fr": "Norberto Proietti",
    "es": "Norberto de Xanten",
  },
  "7-6": {
    "it": "Corpus Domini",
    "en": "Corpus Christi",
    "fr": "Fête-Dieu",
    "es": "Corpus Christi",
  },
  "8-6": {
    "it": "San Medardo",
    "en": "Medardus",
    "fr": "Médard de Noyon",
    "es": "Medardo de Noyon",
  },
  "9-6": {
    "it": "Sant' Efrem",
    "en": "Ephram of Jerusalem",
    "fr": "Éphrem le Syrien",
    "es": "Efrén el Sirio",
  },
  "10-6": {
    "it": "Beata Diana degli Andalò",
    "en": "Diana degli Andalò",
    "fr": "Diane d'Andalo",
    "es": "Diana de Andalo",
  },
  "11-6": {
    "it": "San Barnaba",
    "en": "Epistle of Barnabas",
    "fr": "Épître de Barnabé",
    "es": "Epístola de Bernabé",
  },
  "12-6": {
    "it": "Sacro Cuore di Gesù",
    "en": "Sacred Heart",
    "fr": "Sacré-Cœur de Jésus",
    "es": "Sagrado Corazón de Jesús",
  },
  "13-6": {
    "it": "Sant' Antonio di Padova",
    "en": "Anthony of Padua",
    "fr": "Antoine de Padoue",
    "es": "Antonio de Padua",
  },
  "14-6": {
    "it": "Sant' Eliseo",
    "en": "Elisha",
    "fr": "Élisée",
    "es": "Eliseo",
  },
  "15-6": {
    "it": "San Vito",
    "en": "Saint Vitus",
    "fr": "Guy (saint Vite)",
    "es": "Vito de Lucania",
  },
  "16-6": {
    "it": "Santi Quirico e Giulitta",
    "en": "Cyricus and Julitta",
    "fr": "Cyr et Julitte",
    "es": "Julita y Quirico",
  },
  "17-6": {
    "it": "San Ranieri di Pisa",
    "en": "Leaning Tower of Pisa",
    "fr": "Tour de Pise",
    "es": "Torre de Pisa",
  },
  "18-6": {
    "it": "Santa Marina",
    "en": "Italian Navy ranks",
    "fr": "Marina d'Antioche",
    "es": "Marina de Antioquía",
  },
  "19-6": {
    "it": "San Romualdo",
    "en": "Romuald",
    "fr": "Romuald de Ravenne",
    "es": "Romualdo",
  },
  "20-6": {
    "it": "Beata Vergine Maria Consolatrice",
    "en": "Mary, mother of Jesus",
    "fr": "Marie (mère de Jésus)",
    "es": "María (madre de Jesús)",
  },
  "21-6": {
    "it": "San Luigi Gonzaga",
    "en": "Aloysius Gonzaga",
    "fr": "Louis de Gonzague",
    "es": "Luis Gonzaga",
  },
  "22-6": {
    "it": "San Paolino di Nola",
    "en": "Paulinus of Nola",
    "fr": "Paulin de Nole",
    "es": "Paulino de Nola",
  },
  "23-6": {
    "it": "San Lanfranco Beccari",
    "en": "Lanfranc",
    "fr": "Lanfranc de Cantorbéry",
    "es": "Lanfranco de Pavía",
  },
  "24-6": {
    "it": "Natività di San Giovanni Battista",
    "en": "Nativity of John the Baptist",
    "fr": "Nativité de saint Jean-Baptiste",
    "es": "Natividad de San Juan Bautista",
  },
  "25-6": {
    "it": "San Guglielmo da Vercelli",
    "en": "William of Montevergine",
    "fr": "Guillaume de Verceil",
    "es": "Guillermo de Vercelli",
  },
  "26-6": {
    "it": "San Vigilio",
    "en": "Vigilius of Trent",
    "fr": "Vigile de Trente",
    "es": "Vigilio de Trento",
  },
  "27-6": {
    "it": "San Cirillo d'Alessandria",
    "en": "Cyril of Alexandria",
    "fr": "Cyrille d'Alexandrie",
    "es": "Cirilo de Alejandría",
  },
  "28-6": {
    "it": "Sant' Ireneo di Lione",
    "en": "Irenaeus",
    "fr": "Irénée de Lyon",
    "es": "Ireneo de Lyon",
  },
  "29-6": {
    "it": "Santi Pietro e Paolo",
    "en": "Peter and Paul Fortress",
    "fr": "Forteresse Pierre-et-Paul",
    "es": "Fortaleza de San Pedro y San Pablo",
  },
  "30-6": {
    "it": "Santi Primi martiri della santa Chiesa di Roma",
    "en": "List of churches in Rome",
    "fr": "Liste des églises de Rome",
    "es": "Iglesias de Roma",
  },
  "1-7": {
    "it": "Sant' Aronne",
    "en": "Saint Aaron",
    "fr": "Saint Aaron",
    "es": "San Aarón",
  },
  "2-7": {
    "it": "San Bernardino Realino",
    "en": "Bernardino Realino",
    "fr": "Bernardin Realino",
    "es": "Bernardino Realino",
  },
  "3-7": {
    "it": "San Tommaso",
    "en": "Thomas the Apostle",
    "fr": "Thomas (apôtre)",
    "es": "Tomás el Apóstol",
  },
  "4-7": {
    "it": "Sant' Elisabetta del Portogallo",
    "en": "Elizabeth of York",
    "fr": "Élisabeth d'York",
    "es": "Isabel de York",
  },
  "5-7": {
    "it": "Sant' Antonio Maria Zaccaria",
    "en": "Anthony Zaccaria",
    "fr": "Antoine-Marie Zaccaria",
    "es": "Antonio María Zaccaría",
  },
  "6-7": {
    "it": "Santa Maria Goretti",
    "en": "Maria Goretti",
    "fr": "Maria Goretti",
    "es": "María Goretti",
  },
  "7-7": {
    "it": "Beato Benedetto XI",
    "en": "Pope Benedict XI",
    "fr": "Benoît XI",
    "es": "Benedicto XI",
  },
  "8-7": {
    "it": "Santi Aquila e Priscilla",
    "en": "Priscilla and Aquila",
    "fr": "Aquila (mari de Priscille)",
    "es": "Priscila y Aquila",
  },
  "9-7": {
    "it": "Santa Veronica Giuliani",
    "en": "Veronica Giuliani",
    "fr": "Véronique Giuliani",
    "es": "Verónica Giuliani",
  },
  "10-7": {
    "it": "Sante Rufina e Seconda",
    "en": "Rufina and Secunda",
    "fr": "Rufine et Seconde",
    "es": "Rufina y Segunda",
  },
  "11-7": {
    "it": "San Benedetto da Norcia",
    "en": "Benedict of Nursia",
    "fr": "Benoît de Nursie",
    "es": "Benito de Nursia",
  },
  "12-7": {
    "it": "Santi Ermagora e Fortunato di Aquileia",
    "en": "Hermogoras and Fortunatus",
    "fr": "Hermagoras et Fortunat",
    "es": "Hermágoras y Fortunato",
  },
  "13-7": {
    "it": "Sant' Enrico II",
    "en": "Henry II of France",
    "fr": "Henri II (roi de France)",
    "es": "Enrique II de Francia",
  },
  "14-7": {
    "it": "San Camillo de Lellis",
    "en": "Camillus de Lellis",
    "fr": "Camille de Lellis",
    "es": "Camilo de Lelis",
  },
  "15-7": {
    "it": "San Bonaventura",
    "en": "Bonaventure",
    "fr": "Bonaventure de Bagnoregio",
    "es": "Buenaventura de Bagnoregio",
  },
  "16-7": {
    "it": "Beata Vergine Maria del Monte Carmelo",
    "en": "Our Lady of Mount Carmel",
    "fr": "Notre-Dame du Mont-Carmel",
    "es": "Nuestra Señora del Monte Carmelo",
  },
  "17-7": {
    "it": "Sant' Alessio",
    "en": "Alexius of Rome",
    "fr": "Alexis de Rome",
    "es": "Alejo de Roma",
  },
  "18-7": {
    "it": "San Federico di Utrecht",
    "en": "Frederick of Utrecht",
    "fr": "Frédéric d'Utrecht",
    "es": "Federico de Utrecht",
  },
  "19-7": {
    "it": "Sant' Arsenio il Grande",
    "en": "Arsenius the Great",
    "fr": "Arsène de Scété",
    "es": "Arsenio, el Grande",
  },
  "20-7": {
    "it": "Sant' Elia",
    "en": "Elias of Enna",
    "fr": "Élie d'Enna",
    "es": "Elías el Joven",
  },
  "21-7": {
    "it": "San Lorenzo da Brindisi",
    "en": "Lawrence of Brindisi",
    "fr": "Laurent de Brindes",
    "es": "Lorenzo de Brindis",
  },
  "22-7": {
    "it": "Santa Maria Maddalena",
    "en": "Mary Magdalene",
    "fr": "Marie Madeleine",
    "es": "María Magdalena",
  },
  "23-7": {
    "it": "Santa Brigida di Svezia",
    "en": "Bridget of Sweden",
    "fr": "Brigitte de Suède",
    "es": "Brígida de Suecia",
  },
  "24-7": {
    "it": "Santa Cristina di Bolsena",
    "en": "Christina of Bolsena",
    "fr": "Christine de Tyr",
    "es": "Cristina de Bolsena",
  },
  "25-7": {
    "it": "San Giacomo il Maggiore",
    "en": "James the Great",
    "fr": "Jacques de Zébédée",
    "es": "Santiago el Mayor",
  },
  "26-7": {
    "it": "Santi Anna e Gioacchino",
    "en": "Saints Joachim and Anne",
    "fr": "Saints Joachim et Anne",
    "es": "Santos Joaquín y Ana",
  },
  "27-7": {
    "it": "San Pantaleone",
    "en": "Saint Pantaleon",
    "fr": "Pantaléon de Nicomédie",
    "es": "Pantaleón de Nicomedia",
  },
  "28-7": {
    "it": "Santi Nazario e Celso",
    "en": "Nazarius and Celsus",
    "fr": "Nazaire et Celse",
    "es": "Nazario y Celso",
  },
  "29-7": {
    "it": "Santa Marta di Betania",
    "en": "Martha",
    "fr": "Marthe de Béthanie",
    "es": "Marta de Betania",
  },
  "30-7": {
    "it": "San Pietro Crisologo",
    "en": "Peter Chrysologus",
    "fr": "Pierre Chrysologue",
    "es": "Pedro Crisólogo",
  },
  "31-7": {
    "it": "Sant' Ignazio di Loyola",
    "en": "Ignatius of Loyola",
    "fr": "Ignace de Loyola",
    "es": "Ignacio de Loyola",
  },
  "1-8": {
    "it": "Sant' Alfonso Maria de' Liguori",
    "en": "Alphonsus Liguori",
    "fr": "Alphonse de Liguori",
    "es": "Alfonso María de Ligorio",
  },
  "2-8": {
    "it": "Santa Maria degli Angeli",
    "en": "Our Lady of the Angels",
    "fr": "Notre-Dame des Anges",
    "es": "Virgen de los Ángeles",
  },
  "3-8": {
    "it": "Sant' Aspreno di Napoli",
    "en": "Aspren",
    "fr": "Aspren de Naples",
    "es": "Asprenato de Nápoles",
  },
  "4-8": {
    "it": "San Giovanni Maria Vianney",
    "en": "John Vianney",
    "fr": "Jean-Marie Vianney",
    "es": "Juan María Vianney",
  },
  "5-8": {
    "it": "Santa Maria della Neve",
    "en": "Abbey of Santa Maria della Neve",
    "fr": "Notre-Dame des Neiges",
    "es": "Nuestra Señora de las Nieves",
  },
  "6-8": {
    "it": "Trasfigurazione del Signore",
    "en": "Cathedral Basilica of Salvador",
    "fr": "Transfiguration du Seigneur",
    "es": "Catedral basílica de San Salvador (Salvador de Bahía)",
  },
  "7-8": {
    "it": "San Gaetano Thiene",
    "en": "Gaetano Thiene",
    "fr": "Gaétan de Thiene",
    "es": "Cayetano de Thiene",
  },
  "8-8": {
    "it": "San Domenico di Guzman",
    "en": "Dominic de Guzmán",
    "fr": "Dominique de Guzmán",
    "es": "Domingo de Guzmán",
  },
  "9-8": {
    "it": "Santa Teresa Benedetta della Croce",
    "en": "John of the Cross",
    "fr": "Jean de la Croix",
    "es": "Juan de la Cruz",
  },
  "10-8": {
    "it": "San Lorenzo",
    "en": "Saint Lawrence",
    "fr": "Laurent de Rome",
    "es": "Lorenzo de Roma",
  },
  "11-8": {
    "it": "Santa Chiara",
    "en": "A Chiara",
    "fr": "A Chiara",
    "es": "Clara de Asís",
  },
  "12-8": {
    "it": "Santa Giovanna Francesca de Chantal",
    "en": "Jane Frances de Chantal",
    "fr": "Jeanne de Chantal",
    "es": "Juana Francisca Frémyot de Chantal",
  },
  "13-8": {
    "it": "Santa Filomena di Roma",
    "en": "Philomena",
    "fr": "Philomène (sainte)",
    "es": "Filomena (santa)",
  },
  "14-8": {
    "it": "San Massimiliano Maria Kolbe",
    "en": "Maximilian Kolbe",
    "fr": "Maximilien Kolbe",
    "es": "Maximiliano Kolbe",
  },
  "15-8": {
    "it": "Assunzione della Beata Vergine Maria",
    "en": "Assumption of Mary",
    "fr": "Assomption de Marie",
    "es": "Asunción de María",
  },
  "16-8": {
    "it": "San Rocco",
    "en": "Saint Roch",
    "fr": "Roch de Montpellier",
    "es": "Roque",
  },
  "17-8": {
    "it": "Santa Beatrice de Silva",
    "en": "Beatrice of Silva",
    "fr": "Béatrice de Silva",
    "es": "Beatriz de Silva",
  },
  "18-8": {
    "it": "Sant'Elena Imperatrice",
    "en": "Helena Kantakouzene, Empress of Trebizond",
    "fr": "Hélène Cantacuzène (impératrice de Trébizonde)",
    "es": "Helena Cantacucena (emperatriz de Trebisonda)",
  },
  "19-8": {
    "it": "San Giovanni Eudes",
    "en": "John Eudes",
    "fr": "Jean Eudes",
    "es": "Juan Eudes",
  },
  "20-8": {
    "it": "San Samuele",
    "en": "Samuel of Bulgaria",
    "fr": "Samuel (tsar de Bulgarie)",
    "es": "Samuel de Bulgaria",
  },
  "21-8": {
    "it": "San Pio X",
    "en": "Pope Pius X",
    "fr": "Pie X",
    "es": "Pío X",
  },
  "22-8": {
    "it": "Beata Vergine Maria Regina",
    "en": "Queen of Heaven",
    "fr": "Reine du ciel",
    "es": "Reina de los Cielos",
  },
  "23-8": {
    "it": "Santa Rosa da Lima",
    "en": "Rose of Lima",
    "fr": "Rose de Lima",
    "es": "Rosa de Lima",
  },
  "24-8": {
    "it": "San Bartolomeo",
    "en": "Bartholomew I of Constantinople",
    "fr": "Bartholomée Ier de Constantinople",
    "es": "Bartolomé I",
  },
  "25-8": {
    "it": "Santa Patrizia di Costantinopoli",
    "en": "Patricia of Naples",
    "fr": "Patricia de Constantinople",
    "es": "Patricia de Constantinopla",
  },
  "26-8": {
    "it": "Sant' Alessandro di Bergamo",
    "en": "Alexander of Bergamo",
    "fr": "Alexandre de Bergame",
    "es": "Alejandro de Bérgamo",
  },
  "27-8": {
    "it": "Santa Monica",
    "en": "Gino La Monica",
    "fr": "Monique d'Hippone",
    "es": "Mónica de Hipona",
  },
  "28-8": {
    "it": "Sant' Agostino",
    "en": "Augustine of Canterbury",
    "fr": "Augustin de Cantorbéry",
    "es": "Agustín de Canterbury",
  },
  "29-8": {
    "it": "Martirio di San Giovanni Battista",
    "en": "Beheading of John the Baptist",
    "fr": "Décollation de Jean-Baptiste",
    "es": "Martirio de san Juan Bautista (Masaccio)",
  },
  "30-8": {
    "it": "Santi Felice e Adautto",
    "en": "Felix and Adauctus",
    "fr": "Félix et Adaucte",
    "es": "Félix y Adaucto",
  },
  "31-8": {
    "it": "San Raimondo Nonnato",
    "en": "Raymond Nonnatus",
    "fr": "Raymond Nonnat",
    "es": "Ramón Nonato",
  },
  "1-9": {
    "it": "Sant' Egidio",
    "en": "Egidio Maria of Saint Joseph",
    "fr": "Égide-Marie de Saint-Joseph",
    "es": "Gil María de San José",
  },
  "2-9": {
    "it": "Sant' Elpidio",
    "en": "Elpidius of Atella",
    "fr": "Saint Elpide",
    "es": "San Elpidio",
  },
  "3-9": {
    "it": "San Gregorio Magno",
    "en": "Order of St. Gregory the Great",
    "fr": "Ordre de Saint-Grégoire-le-Grand",
    "es": "Orden de San Gregorio Magno",
  },
  "4-9": {
    "it": "Santa Rosalia",
    "en": "Saint Rosalia",
    "fr": "Rosalie de Palerme",
    "es": "Rosalía de Palermo",
  },
  "5-9": {
    "it": "Santa Teresa di Calcutta",
    "en": "Mother Teresa",
    "fr": "Mère Teresa",
    "es": "Teresa de Calcuta",
  },
  "6-9": {
    "it": "San Zaccaria",
    "en": "Zechariah, father of John the Baptist",
    "fr": "Zacharie (père de Jean le Baptiste)",
    "es": "Zacarías (padre de Juan el Bautista)",
  },
  "7-9": {
    "it": "Santa Regina di Alise",
    "en": "Regina of Autun",
    "fr": "Reine (sainte)",
    "es": "Regina de Alesia",
  },
  "8-9": {
    "it": "Natività della Beata Vergine Maria",
    "en": "Nativity of Mary",
    "fr": "Nativité de Marie",
    "es": "Natividad de la Virgen",
  },
  "9-9": {
    "it": "San Pietro Claver",
    "en": "Knights of Peter Claver",
    "fr": "Pierre Claver",
    "es": "Pedro Claver",
  },
  "10-9": {
    "it": "San Nicola da Tolentino",
    "en": "Nicholas of Tolentino",
    "fr": "Nicolas de Tolentino",
    "es": "Nicolás de Tolentino",
  },
  "11-9": {
    "it": "Santi Proto e Giacinto",
    "en": "Protus and Hyacinth",
    "fr": "Prote et Hyacinthe",
    "es": "Proto y Jacinto",
  },
  "12-9": {
    "it": "Santissimo Nome di Maria",
    "en": "Most Holy Name of the Blessed Virgin Mary",
    "fr": "Fête du Saint Nom de Marie",
    "es": "Dulce Nombre de la Virgen María",
  },
  "13-9": {
    "it": "San Giovanni Crisostomo",
    "en": "John Chrysostom",
    "fr": "Jean Chrysostome",
    "es": "Juan Crisóstomo",
  },
  "14-9": {
    "it": "Esaltazione della Santa Croce",
    "en": "Feast of the Cross",
    "fr": "Fête de la Croix",
    "es": "Exaltación de la Santa Cruz",
  },
  "15-9": {
    "it": "Beata Vergine Maria Addolorata",
    "en": "Our Lady of Sorrows",
    "fr": "Mater dolorosa",
    "es": "Nuestra Señora de los Dolores",
  },
  "16-9": {
    "it": "Santi Cipriano e Cornelio",
    "en": "Cyprian and Cornelius",
    "fr": "Cyprien et Corneille",
    "es": "Cipriano y Cornelio",
  },
  "17-9": {
    "it": "San Roberto Bellarmino",
    "en": "Robert Bellarmine",
    "fr": "Robert Bellarmin",
    "es": "Roberto Belarmino",
  },
  "18-9": {
    "it": "San Giuseppe da Copertino",
    "en": "Joseph of Cupertino",
    "fr": "Joseph de Cupertino",
    "es": "José de Cupertino",
  },
  "19-9": {
    "it": "San Gennaro",
    "en": "Royal Chapel of the Treasure of St. Januarius",
    "fr": "Chapelle royale du Trésor de San Gennaro",
    "es": "Capilla Real del Tesoro di San Gennaro",
  },
  "20-9": {
    "it": "Santi Martiri Coreani",
    "en": "103 Korean martyrs",
    "fr": "Martyrs de Corée",
    "es": "Mártires de Corea",
  },
  "21-9": {
    "it": "San Matteo",
    "en": "Santino Di Matteo",
    "fr": "Matthieu l'Évangéliste",
    "es": "Santino di Matteo",
  },
  "22-9": {
    "it": "San Maurizio",
    "en": "Saint Maurice",
    "fr": "Maurice d'Agaune",
    "es": "Mauricio el Tebano",
  },
  "23-9": {
    "it": "San Pio da Pietrelcina",
    "en": "Sanctuary of Saint Pio of Pietrelcina",
    "fr": "Pio de Pietrelcina",
    "es": "Pío de Pietrelcina",
  },
  "24-9": {
    "it": "Beata Vergine Maria della Mercede",
    "en": "Order of the Blessed Virgin Mary of Mercy",
    "fr": "Ordre de Notre-Dame de la Merci",
    "es": "Orden de la Merced",
  },
  "25-9": {
    "it": "San Cleofa",
    "en": "Cleopas",
    "fr": "Cléophas",
    "es": "Cleofás",
  },
  "26-9": {
    "it": "Santi Cosma e Damiano",
    "en": "Cosmas and Damian",
    "fr": "Côme et Damien",
    "es": "Cosme y Damián",
  },
  "27-9": {
    "it": "San Vincenzo de' Paoli",
    "en": "Daughters of Charity of Saint Vincent de Paul",
    "fr": "Filles de la charité de saint Vincent de Paul",
    "es": "Hijas de la Caridad de San Vicente de Paúl",
  },
  "28-9": {
    "it": "San Venceslao",
    "en": "Wenceslaus IV of Bohemia",
    "fr": "Venceslas de Luxembourg",
    "es": "Wenceslao de Luxemburgo",
  },
  "29-9": {
    "it": "Santi Michele, Gabriele e Raffaele",
    "en": "Gabriel",
    "fr": "Gabriel (archange)",
    "es": "Arcángel Gabriel",
  },
  "30-9": {
    "it": "San Girolamo",
    "en": "Jerome",
    "fr": "Jérôme de Stridon",
    "es": "Jerónimo (santo)",
  },
  "1-10": {
    "it": "Santa Teresa di Lisieux",
    "en": "Thérèse of Lisieux",
    "fr": "Thérèse de Lisieux",
    "es": "Teresa de Lisieux",
  },
  "2-10": {
    "it": "Santi Angeli Custodi",
    "en": "Guardian Angels",
    "fr": "Saints Anges gardiens",
    "es": "Santos Ángeles Custodios",
  },
  "3-10": {
    "it": "San Gerardo di Brogne",
    "en": "Gérard of Brogne",
    "fr": "Gérard de Brogne",
    "es": "Gerardo de Namur",
  },
  "4-10": {
    "it": "San Francesco d'Assisi",
    "en": "Francisco de Asís, Duke of Cádiz",
    "fr": "François d'Assise de Bourbon",
    "es": "Francisco de Asís de Borbón",
  },
  "5-10": {
    "it": "Santa Maria Faustina Kowalska",
    "en": "Faustina Kowalska",
    "fr": "Faustine Kowalska",
    "es": "María Faustina Kowalska",
  },
  "6-10": {
    "it": "San Bruno di Colonia",
    "en": "Bruno of Cologne",
    "fr": "Bruno le Chartreux",
    "es": "Bruno de Colonia",
  },
  "7-10": {
    "it": "Beata Vergine Maria del Rosario",
    "en": "Shrine of the Virgin of the Rosary of Pompei",
    "fr": "Sanctuaire Notre-Dame-du-Rosaire de Pompéi",
    "es": "Santuario de la Beata Virgen del Rosario",
  },
  "8-10": {
    "it": "Santa Pelagia di Antiochia",
    "en": "Pelagia",
    "fr": "Pélagie d'Antioche",
    "es": "Pelagia de Antioquía",
  },
  "9-10": {
    "it": "San Dionigi e compagni",
    "en": "Denis of Paris",
    "fr": "Denis de Paris",
    "es": "Dionisio de París",
  },
  "10-10": {
    "it": "San Daniele Comboni",
    "en": "Daniele Comboni",
    "fr": "Daniel Comboni",
    "es": "Daniel Comboni",
  },
  "11-10": {
    "it": "San Giovanni XXIII",
    "en": "Pope John XXIII",
    "fr": "Jean XXIII",
    "es": "Juan XXIII",
  },
  "12-10": {
    "it": "San Carlo Acutis",
    "en": "Carlo Acutis",
    "fr": "Carlo Acutis",
    "es": "Carlo Acutis",
  },
  "13-10": {
    "it": "San Teofilo di Antiochia",
    "en": "Theophilus of Antioch",
    "fr": "Théophile d'Antioche",
    "es": "Teófilo de Antioquía",
  },
  "14-10": {
    "it": "San Callisto I",
    "en": "Pope Callixtus I",
    "fr": "Calixte Ier",
    "es": "Calixto I",
  },
  "15-10": {
    "it": "Santa Teresa d'Avila",
    "en": "Ecstasy of Saint Teresa",
    "fr": "L'Extase de sainte Thérèse",
    "es": "Éxtasis de Santa Teresa",
  },
  "16-10": {
    "it": "Santa Margherita Maria Alacoque",
    "en": "Margaret Mary Alacoque",
    "fr": "Marguerite-Marie Alacoque",
    "es": "Margarita María Alacoque",
  },
  "17-10": {
    "it": "Sant' Ignazio di Antiochia",
    "en": "Ignatius of Antioch",
    "fr": "Ignace d'Antioche",
    "es": "Ignacio de Antioquía",
  },
  "18-10": {
    "it": "San Luca",
    "en": "Luke the Evangelist",
    "fr": "Luc (évangéliste)",
    "es": "Lucas el Evangelista",
  },
  "19-10": {
    "it": "San Paolo della Croce",
    "en": "Paul of the Cross",
    "fr": "Sœurs passionistes de Saint Paul de la Croix",
    "es": "Hermanas Pasionistas de San Pablo de la Cruz",
  },
  "20-10": {
    "it": "Santa Maria Bertilla Boscardin",
    "en": "Maria Bertilla Boscardin",
    "fr": "Maria Bertilla Boscardin",
    "es": "María Bertila Boscardin",
  },
  "21-10": {
    "it": "Beato Giuseppe Puglisi",
    "en": "Blessed Giuseppe Puglisi",
    "fr": "Bienheureux Giuseppe Puglisi",
    "es": "Beato Giuseppe Puglisi",
  },
  "22-10": {
    "it": "San Giovanni Paolo II",
    "en": "Death and funeral of Pope John Paul II",
    "fr": "Mort et funérailles de Jean-Paul II",
    "es": "Muerte y funeral de Juan Pablo II",
  },
  "23-10": {
    "it": "San Giovanni da Capestrano",
    "en": "John of Capistrano",
    "fr": "Jean de Capistran",
    "es": "Juan de Capistrano",
  },
  "24-10": {
    "it": "Sant' Antonio Maria Claret",
    "en": "Anthony Mary Claret",
    "fr": "Antoine-Marie Claret",
    "es": "Antonio María Claret",
  },
  "25-10": {
    "it": "Santi Crisante e Daria",
    "en": "Chrysanthus and Daria",
    "fr": "Crisant et Daria",
    "es": "Crisanto y Daría",
  },
  "26-10": {
    "it": "San Folco Scotti",
    "en": "Fulk of Pavia",
    "fr": "Foulques Scotti",
    "es": "Fulco de Pavía",
  },
  "27-10": {
    "it": "Sant' Evaristo",
    "en": "Pope Evaristus",
    "fr": "Évariste (pape)",
    "es": "Evaristo",
  },
  "28-10": {
    "it": "Santi Simone e Giuda",
    "en": "Jude Thaddeus the Apostle",
    "fr": "Jude (apôtre)",
    "es": "Judas Tadeo",
  },
  "29-10": {
    "it": "Beata Chiara Luce Badano",
    "en": "Chiara Badano",
    "fr": "Chiara Badano",
    "es": "Chiara Badano",
  },
  "30-10": {
    "it": "San Germano di Capua",
    "en": "Germanus of Capua",
    "fr": "Germain de Capoue",
    "es": "Germán de Capua",
  },
  "31-10": {
    "it": "Santa Lucilla di Roma",
    "en": "Lucilla of Rome",
    "fr": "Lucille de Rome",
    "es": "Lucila de Roma",
  },
  "1-11": {
    "it": "Tutti i Santi",
    "en": "All Saints' Day",
    "fr": "Toussaint",
    "es": "Todos los Santos",
  },
  "2-11": {
    "it": "Commemorazione di tutti i fedeli defunti",
    "en": "All Souls' Day",
    "fr": "Commémoration de tous les fidèles défunts",
    "es": "Día de los Fieles Difuntos",
  },
  "3-11": {
    "it": "Santa Silvia",
    "en": "Saint Sylvia",
    "fr": "Silvia de Rome",
    "es": "Silvia de Roma",
  },
  "4-11": {
    "it": "San Carlo Borromeo",
    "en": "Sancarlone",
    "fr": "Colosse de Saint Charles Borromée",
    "es": "Coloso de San Carlo Borromeo",
  },
  "5-11": {
    "it": "San Guido Maria Conforti",
    "en": "Guido Maria Conforti",
    "fr": "Guy Marie Conforti",
    "es": "Guido María Conforti",
  },
  "6-11": {
    "it": "San Leonardo di Noblac",
    "en": "Leonard of Noblac",
    "fr": "Léonard de Noblat",
    "es": "Leonardo de Noblat",
  },
  "7-11": {
    "it": "San Prosdocimo di Padova",
    "en": "Prosdocimus",
    "fr": "Prosdocime de Padoue",
    "es": "Prosdócimo de Padua",
  },
  "8-11": {
    "it": "San Goffredo di Amiens",
    "en": "Geoffrey of Amiens",
    "fr": "Geoffroy d'Amiens",
    "es": "Godofredo de Amiens",
  },
  "9-11": {
    "it": "Dedicazione della Basilica Lateranense",
    "en": "Dedication of the Lateran Basilica",
    "fr": "Dédicace de la basilique du Latran",
    "es": "Dedicación de la Basílica de Letrán",
  },
  "10-11": {
    "it": "San Leone Magno",
    "en": "Pope Leo I",
    "fr": "Léon Ier",
    "es": "León I",
  },
  "11-11": {
    "it": "San Martino di Tours",
    "en": "Martin of Tours",
    "fr": "Martin de Tours",
    "es": "Martín de Tours",
  },
  "12-11": {
    "it": "San Giosafat Kuncewycz",
    "en": "Josaphat Kuntsevych",
    "fr": "Josaphat Kountsevitch",
    "es": "Josafat Kuncewicz",
  },
  "13-11": {
    "it": "San Diego di Alcalà",
    "en": "Saint Didacus of Alcalá Presenting Juan de Herrera's Son to Christ",
    "fr": "Didace d'Alcalá",
    "es": "Diego de Alcalá",
  },
  "14-11": {
    "it": "San Lorenzo O'Toole",
    "en": "Lorcán Ua Tuathail",
    "fr": "Laurent O’Toole",
    "es": "Lorenzo O'Toole",
  },
  "15-11": {
    "it": "Sant' Alberto Magno",
    "en": "Albertus Magnus",
    "fr": "Albert le Grand",
    "es": "Alberto Magno",
  },
  "16-11": {
    "it": "Santa Margherita di Scozia",
    "en": "Margaret, Maid of Norway",
    "fr": "Marguerite de Norvège",
    "es": "Margarita I de Escocia",
  },
  "17-11": {
    "it": "Sant' Elisabetta d'Ungheria",
    "en": "Elizabeth of Hungary",
    "fr": "Élisabeth de Hongrie",
    "es": "Isabel de Hungría",
  },
  "18-11": {
    "it": "Dedicazione delle basiliche dei Santi Pietro e Paolo",
    "en": "Paul the Apostle",
    "fr": "Paul de Tarse",
    "es": "Pablo de Tarso",
  },
  "19-11": {
    "it": "Santa Matilde di Hackeborn",
    "en": "Mechthild of Hackeborn",
    "fr": "Mechtilde de Hackeborn",
    "es": "Matilde de Hackeborn",
  },
  "20-11": {
    "it": "Sant' Edmondo",
    "en": "Edmund of Abingdon",
    "fr": "Edmond Rich d'Abingdon",
    "es": "Edmundo de Abingdon",
  },
  "21-11": {
    "it": "Presentazione della Beata Vergine Maria",
    "en": "Presentation of Mary",
    "fr": "Présentation de Marie au Temple",
    "es": "Presentación de María",
  },
  "22-11": {
    "it": "Solennità di Cristo Re",
    "en": "Christ the King",
    "fr": "Christ Roi",
    "es": "Cristo Rey",
  },
  "23-11": {
    "it": "San Clemente I Romano",
    "en": "Clement of Rome",
    "fr": "Clément de Rome",
    "es": "Clemente de Roma",
  },
  "24-11": {
    "it": "Santa Flora di Cordova",
    "en": "Flora of Córdoba",
    "fr": "Flore de Cordoue",
    "es": "Flora de Córdoba",
  },
  "25-11": {
    "it": "Santa Caterina d'Alessandria",
    "en": "Catherine of Alexandria",
    "fr": "Sainte Catherine d'Alexandrie (Le Caravage)",
    "es": "Catalina de Alejandría",
  },
  "26-11": {
    "it": "San Leonardo da Porto Maurizio",
    "en": "Leonard of Port Maurice",
    "fr": "Léonard de Port-Maurice",
    "es": "Leonardo de Puerto Mauricio",
  },
  "27-11": {
    "it": "Beata Vergine della Medaglia Miracolosa",
    "en": "Miraculous Medal",
    "fr": "Médaille miraculeuse",
    "es": "Medalla Milagrosa",
  },
  "28-11": {
    "it": "San Giacomo della Marca",
    "en": "James of the Marches",
    "fr": "Jacques de la Marche",
    "es": "Jaime de la Marca",
  },
  "29-11": {
    "it": "San Saturnino di Tolosa",
    "en": "Saturnin",
    "fr": "Saturnin de Toulouse",
    "es": "Saturnino de Tolosa",
  },
  "30-11": {
    "it": "Sant' Andrea",
    "en": "Andrew the Apostle",
    "fr": "André (apôtre)",
    "es": "Andrés el Apóstol",
  },
  "1-12": {
    "it": "Sant' Eligio",
    "en": "Saint Eligius",
    "fr": "Éloi de Noyon",
    "es": "Eligio",
  },
  "2-12": {
    "it": "Santa Bibiana",
    "en": "Bibiana of Rome",
    "fr": "Bibiane",
    "es": "Bibiana (santa)",
  },
  "3-12": {
    "it": "San Francesco Saverio",
    "en": "Francis Xavier",
    "fr": "François Xavier",
    "es": "Francisco Javier",
  },
  "4-12": {
    "it": "Santa Barbara",
    "en": "Saint Barbara",
    "fr": "Barbe de Nicomédie",
    "es": "Bárbara de Nicomedia",
  },
  "5-12": {
    "it": "San Saba Archimandrita",
    "en": "Sabbas the Sanctified",
    "fr": "Sabas le Sanctifié",
    "es": "Sabas el Santificado",
  },
  "6-12": {
    "it": "San Nicola di Bari",
    "en": "Saint Nicholas",
    "fr": "Nicolas de Myre",
    "es": "Nicolás de Bari",
  },
  "7-12": {
    "it": "Sant' Ambrogio",
    "en": "Ambrogio",
    "fr": "Ambroise de Milan",
    "es": "Ambrogio",
  },
  "8-12": {
    "it": "Immacolata Concezione della Beata Vergine Maria",
    "en": "Immaculate Conception",
    "fr": "Immaculée Conception",
    "es": "Inmaculada Concepción",
  },
  "9-12": {
    "it": "San Siro di Pavia",
    "en": "Syrus of Pavia",
    "fr": "Syr de Pavie",
    "es": "Siro de Pavía",
  },
  "10-12": {
    "it": "Beata Vergine Maria di Loreto",
    "en": "Our Lady of Loreto",
    "fr": "Notre-Dame de Lorète",
    "es": "Nuestra Señora de Loreto",
  },
  "11-12": {
    "it": "San Damaso I",
    "en": "Pope Damasus I",
    "fr": "Damase Ier",
    "es": "Dámaso I",
  },
  "12-12": {
    "it": "Beata Maria Vergine di Guadalupe",
    "en": "Our Lady of Guadalupe",
    "fr": "Notre-Dame de Guadalupe (homonymie)",
    "es": "Virgen de Guadalupe",
  },
  "13-12": {
    "it": "Santa Lucia",
    "en": "Saint Lucy",
    "fr": "Lucie de Syracuse",
    "es": "Lucía de Siracusa",
  },
  "14-12": {
    "it": "San Giovanni della Croce",
    "en": "John of the Cross",
    "fr": "Jean de la Croix",
    "es": "Juan de la Cruz",
  },
  "15-12": {
    "it": "Santa Virginia Centurione Bracelli",
    "en": "Virginia Centurione Bracelli",
    "fr": "Virginie Centurione Bracelli",
    "es": "Virginia Centurione Bracelli",
  },
  "16-12": {
    "it": "Sant' Adelaide",
    "en": "Adelaide of Italy",
    "fr": "Adélaïde de Bourgogne",
    "es": "Adelaida de Italia",
  },
  "17-12": {
    "it": "San Giovanni de Matha",
    "en": "John of Matha",
    "fr": "Jean de Matha",
    "es": "Juan de Mata",
  },
  "18-12": {
    "it": "San Gaziano di Tours",
    "en": "Gatianus of Tours",
    "fr": "Gatien de Tours",
    "es": "Gaciano de Tours",
  },
  "19-12": {
    "it": "San Dario",
    "en": "Darius of Nicomedia",
    "fr": "Darius de Nicomédie",
    "es": "Darío de Nicomedia",
  },
  "20-12": {
    "it": "San Liberato (Liberale)",
    "en": "Saint Liberatus",
    "fr": "Saint Libérat",
    "es": "San Liberato",
  },
  "21-12": {
    "it": "San Pietro Canisio",
    "en": "Peter Canisius",
    "fr": "Pierre Canisius",
    "es": "Pedro Canisio",
  },
  "22-12": {
    "it": "Santa Francesca Saverio Cabrini",
    "en": "Frances Xavier Cabrini",
    "fr": "Françoise-Xavière Cabrini",
    "es": "Francisca Javiera Cabrini",
  },
  "23-12": {
    "it": "Santa Vittoria",
    "en": "Victoria of Rome",
    "fr": "Victoire de Rome",
    "es": "Victoria de Roma",
  },
  "24-12": {
    "it": "San Delfino di Bordeaux",
    "en": "Delphinus of Bordeaux",
    "fr": "Delphin de Bordeaux",
    "es": "Delfín de Burdeos",
  },
  "25-12": {
    "it": "Natale del Signore",
    "en": "Christmas",
    "fr": "Noël",
    "es": "Navidad",
  },
  "26-12": {
    "it": "Santo Stefano",
    "en": "Saint Stephen",
    "fr": "Saint Étienne",
    "es": "San Esteban",
  },
  "27-12": {
    "it": "Santa Famiglia di Gesù, Maria e Giuseppe",
    "en": "Holy Family",
    "fr": "Sainte Famille",
    "es": "Sagrada Familia",
  },
  "28-12": {
    "it": "Santi Innocenti",
    "en": "Holy Innocents",
    "fr": "Saints Innocents",
    "es": "Santos Inocentes",
  },
  "29-12": {
    "it": "San Davide",
    "en": "Saint David",
    "fr": "Saint David",
    "es": "San David",
  },
  "30-12": {
    "it": "Sant' Eugenio di Milano",
    "en": "Eugene of Milan",
    "fr": "Eugène de Milan",
    "es": "Eugenio de Milán",
  },
  "31-12": {
    "it": "San Silvestro I",
    "en": "Pope Sylvester I",
    "fr": "Sylvestre Ier",
    "es": "Silvestre I",
  },
};
