name: Screenshots Generator

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Screenshots
        run: flutter test test/screenshots_test.dart --update-goldens --dart-define=SONARPAD_ROUTE_CLIENT_TOKEN=${{ secrets.SONARPAD_ROUTE_CLIENT_TOKEN }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: home-screenshots
          path: test/goldens/
